/* Interactive ENT previews translated from Cliently page variants. All actions stay local. */
const KIT_VIEWS=[['components','Components'],['emails','Emails Page'],['tasks','Tasks Page'],['settings','Settings Page'],['help','Help & Center'],['notes','Note Page']];
const KIT_SOURCE={emails:'6233:51422',tasks:'6233:51571',notes:'6233:51526',settings:'6233:51898',help:'6233:51880'};
const PAGE_ICONS={
 edit:['80db4.svg','ff36d.svg'],share:['50fbd.svg','2c0a8.svg'],trash:['5481c.svg','c78c0.svg'],
 archive:['e3287.svg','bd625.svg'],unread:['04baa.svg','2cf73.svg'],reply:['46228.svg','1211d.svg'],
 profile:['d0d38.svg','826c2.svg'],calendar:['14e5d.svg','79f91.svg'],storage:['2f18c.svg','53364.svg'],
 refer:['9f2f2.svg','b9114.svg'],notification:['3e198.svg','ca4e6.svg'],workspace:['6137f.svg','5e1ed.svg'],
 members:['affad.svg','fa937.svg'],plans:['982d1.svg','7dfd4.svg'],integration:['2c8ea.svg','9cb65.svg'],
 info:['d2677.svg','edd79.svg'],more:['04859.svg','95bac.svg'],copy:['fc18d.svg','a9704.svg'],chat:['106cf.svg','9bf97.svg'],email:['885d9.svg','f5320.svg'],phone:['61b57.svg','b5355.svg']
};
function pageAsset(name,other=name,size=null,extra=''){
 const d=PAGE_DIMENSIONS[name];if(!d)return '';
 const bitmap=!name.endsWith('.svg'),w=bitmap&&size?size:parseFloat(d.width),h=bitmap&&size?size:parseFloat(d.height);
 return themedAsset('assets/cliently/pages/'+name,'assets/cliently/pages/'+other,w,h,extra);
}
const pageIcon=name=>isV2()?elevenIcon(name):pageAsset(...(PAGE_ICONS[name]||[name,name]),null,'class="page-glyph"');
const kitButton=(label,action,style='',extra='')=>`<button type="button" class="btn ${style}" data-kit-action="${action}" ${extra}>${label}</button>`;
const kitIconButton=(label,action,glyph,extra='')=>`<button type="button" class="iconbtn" aria-label="${esc(label)}" data-kit-action="${action}" ${extra}>${pageIcon(glyph)}</button>`;
const kitAvatar=(n,size=24)=>pageAsset(['dd1fe.png','e235c.png','ad848.png','27083.png'][n%4],undefined,size,'class="avatar-image"');
const KIT_NOTE_COLORS={green:'#EFFCD3',purple:'#DCD9FE',peach:'#FFE7D6',yellow:'#FFF7D1',blue:'#DBECFD'};
const kitDemo={
 query:{emails:'',tasks:'',notes:'',help:'',integration:''},mailFolder:'all',mailSelected:1,mailMobile:false,mailFacility:'all',reply:false,
 tasksView:'list',taskGroup:'all',taskFacility:'all',menu:null,settings:'profile',article:null,faq:0,moreHelp:false,linkedKey:null,
 emails:[
  {id:1,name:'Casey Brooks',email:'casey@example.test',subject:'RE: Sunrise Villa clinic preparation',body:'Hi Jordan,\n\nThank you for preparing the census review for Sunrise Villa. The next clinic can be planned once staff confirm the resident list and consent records.\n\nPlease review these items before the clinic:\n• Resolve possible patient matches before using visit history.\n• Confirm the selected insurance outcome.\n• Review scheduling and Courtesy decisions with the clinic.\n\nThe attached workflow is a fictional demonstration. No resident records or documents are included in this email.\n\nThanks,\nCasey',facility:'Sunrise Villa',read:true,archive:false,avatar:0},
  {id:2,name:'Morgan Lee',email:'morgan@example.test',subject:'Oak Terrace — clinic date confirmed',body:'Hi Jordan,\n\nThe sample clinic date is confirmed. Please check the facility resident list and prepare the consent summary.\n\nThank you,\nMorgan',facility:'Oak Terrace',read:false,archive:false,avatar:1},
  {id:3,name:'Sam Ellis',email:'sam@example.test',subject:'Face sheet intake — review needed',body:'Please review the extracted demographics beside the source document. Confirm whether to create a new patient or link the sample existing patient.\n\nThis is a fictional intake record.',facility:'Bayview',read:false,archive:false,avatar:2},
  {id:4,name:'Alex Taylor',email:'alex@example.test',subject:'Census follow-up checklist',body:'The sample census has several residents marked Follow-up due. Please complete matching and insurance review before assigning the clinic schedule.',facility:'Sunrise Villa',read:true,archive:false,avatar:3},
  {id:5,name:'Jamie Reed',email:'jamie@example.test',subject:'Consent collection update',body:'Please check the consent collection progress in Facilities. The sample consent threshold is shown on each facility card.',facility:'Oak Terrace',read:false,archive:false,avatar:1},
  {id:6,name:'Casey Brooks',email:'casey@example.test',subject:'Attachment retry completed',body:'The fictional attachment was saved to the same patient ID. A second patient record was not created.',facility:'Bayview',read:true,archive:false,avatar:0},
  {id:7,name:'Morgan Lee',email:'morgan@example.test',subject:'Previous clinic summary',body:'This archived message contains a sample clinic preparation summary.',facility:'Sunrise Villa',read:true,archive:true,avatar:1}
 ],
 tasks:[
  ['Review Sunrise Villa census','Today',0,'Todo','Today'],['Resolve possible patient match','Today',1,'Inprogress','Late'],['Prepare clinic consent summary','Today',2,'Review','Safe'],
  ['Confirm Oak Terrace clinic date','This Week',1,'Todo','Safe'],['Review face sheet demographics','This Week',0,'Inprogress','Safe'],['Follow up on attachment retry','This Week',2,'Todo','Safe'],['Prepare facility welcome email','This Week',1,'Todo','Safe'],
  ['Review Bayview resident list','Upcoming',2,'Todo','Safe'],['Prepare next clinic checklist','Upcoming',0,'Todo','Safe'],['Confirm sample consent records','Completed',0,'Completed','Today']
 ].map(([title,group,facility,status,due],i)=>({id:i+1,title,group,facility,status,due,assigned:i%3,body:'Review the fictional care workflow and confirm the relevant staff decisions before completing this task.',checklist:[false,false,false]})),
 notes:[
  ['Clinic preparation — Sunrise Villa','Review census results and confirm consent before scheduling the next ENT clinic.','green',true],
  ['Patient matching checklist','Confirm spelling and date of birth before using the sample visit history.','purple',true],
  ['Intake review — Oak Terrace','Compare extracted demographics with the source. Confirm create or link before approval.','peach',true],
  ['Consent collection guide','Review the facility consent summary and identify the person who will sign.','yellow',false],
  ['Onboarding — Care coordinators','• Review facility directory\n• Complete the sample census walkthrough','green',false],
  ['Clinic planning — Internal team','Confirm the clinic date, staff assignments and consent threshold with the clinic.','peach',false],
  ['Follow-up checklist','• Resolve patient matching\n• Confirm review decisions\n• Prepare the clinic list','blue',false],
  ['Attachment retry feedback','Keep the saved patient ID when retrying an attachment. Avoid creating a second patient.','peach',false],
  ['Internal content requests','• Add a census guide\n• Explain all intake states\n• Prepare a demo checklist','purple',false]
 ].map(([title,body,color,favorite],i)=>({id:i+1,title,body,color,favorite,author:'Jordan Davis',day:'Oct 7, 2026'})),
 profile:{first:'Jordan',last:'Davis',phone:'+12025550100',email:'jordan@example.test',timezone:'UTC + 7',week:'Monday'},profileDraft:null,
 workspace:{name:'ENT Care',email:'workspace@example.test',industry:'Healthcare',currency:'USD ($)'},workspaceDraft:null,
 notifications:{Mentions:true,Replies:true,'Email Grants':true,'Task Assignments':true,'Shared Resources':true},watermark:true,
 connections:{},plan:'Pro Plan',monthly:false,avatar:null,avatarRemoved:false,workspaceAvatar:null,workspaceAvatarRemoved:false,
 members:[{id:1,name:'Jordan Davis',email:'jordan@example.test',role:'Admin'},{id:2,name:'Casey Brooks',email:'casey@example.test',role:'Coordinator'},{id:3,name:'Sam Ellis',email:'sam@example.test',role:'Staff'}],
 integrations:[['Census','Automation','3ac4f.svg'],['Fillout','Forms & surveys','5f792.png'],['Mailchimp','E-mail sequencing','0501e.svg'],['Polytomic','Data','ebcf7.png'],['Relay','Automation','23a74.png'],['Typeform','Forms & surveys','04791.svg'],['Circleback','Call recording','c8e77.png'],['Clay','Data','2bbf2.png'],['Hightouch','Automation','d1418.png'],['June','Analytics','59100.png'],['Mixmax','E-mail sequencing','810f1.svg'],['Outreach','E-mail sequencing','c875e.svg'],['Popsink','Data','145c8.png'],['Segment','Analytics','78097.svg'],['Zapier','Automation','e0154.svg']].map(([name,category,asset],i)=>({id:i+1,name,category,asset,on:false,removed:false})),
 integrationFilter:'all'
};
function kitView(){const v=new URLSearchParams(location.hash.split('?')[1]||'').get('view');return KIT_VIEWS.some(([id])=>id===v)?v:'components';}
function kitSearch(kind,placeholder){return `<label class="search kit-search">${icon('search')}<span class="visually-hidden">${placeholder}</span><input data-kit-search="${kind}" placeholder="${placeholder}" value="${esc(kitDemo.query[kind]||'')}"></label>`;}
function kitPages(){
 if(isV2())return v2KitPage();
 const view=kitView();
 const nav=`<nav class="kit-page-tabs" role="tablist" aria-label="UI Kit pages">${KIT_VIEWS.map(([id,label])=>`<a role="tab" aria-selected="${view===id}" aria-controls="kit-view" id="kit-tab-${id}" tabindex="${view===id?'0':'-1'}" href="#kit${id==='components'?'':'?view='+id}">${label}</a>`).join('')}</nav>`;
 const ctas={emails:kitButton(`${icon('plus')}New Messages`,'compose','primary'),tasks:kitButton(`${icon('plus')}New Task`,'new-task','primary'),notes:kitButton(`${icon('plus')}Create Note`,'new-note','primary'),settings:kitButton('Set Default','settings-default')+kitButton('Save Changes','settings-save','primary'),help:'',components:button('Reset demo','reset-demo')};
 const header=`<div class="page-actions">${ctas[view]}</div>`;
 const content=view==='components'?pageHead('Cliently design system','Shared components and functional page previews from Figma.')+componentGallery():({emails:kitEmails,tasks:kitTasks,notes:kitNotes,settings:kitSettings,help:kitHelp})[view]();
 return header+nav+(view==='notes'?`<div class="kit-mobile-search">${kitSearch(view,'Search Note')}</div>`:'')+`<div id="kit-view" class="kit-functional kit-${view}" role="tabpanel" aria-labelledby="kit-tab-${view}">${content}</div>`;
}
function underTabs(items,active,action){return `<div class="under-tabs" role="tablist">${items.map(([value,label])=>`<button type="button" role="tab" aria-selected="${active===value}" data-kit-action="${action}" data-value="${value}">${label}</button>`).join('')}</div>`;}
function kitEmails(){
 const mails=kitDemo.emails.filter(m=>(kitDemo.mailFolder==='archive'?m.archive:!m.archive)&&(kitDemo.mailFolder!=='unread'||!m.read||(kitDemo.mailMobile&&m.id===kitDemo.mailSelected))&&(kitDemo.mailFacility==='all'||m.facility===kitDemo.mailFacility)&&(m.subject+' '+m.name+' '+m.body).toLowerCase().includes(kitDemo.query.emails.toLowerCase()));
 let selected=mails.find(m=>m.id===kitDemo.mailSelected)||mails[0];
 const detail=selected?`<header class="mail-detail-head"><div class="mail-sender">${pageAsset('78c9f.png',undefined,40,'class="avatar-image"')}<div><strong>${esc(selected.name)}</strong><small>${esc(selected.email)}</small><p>Received <strong>Jordan Davis</strong></p></div></div><div class="mail-actions"><small>7 Oct 2026</small>${kitIconButton('Mark as '+(selected.read?'unread':'read'),'mail-read','unread',`data-id="${selected.id}"`)}${kitIconButton(selected.archive?'Restore email':'Archive email','mail-archive','archive',`data-id="${selected.id}"`)}${kitIconButton('Reply to email','reply','reply',`data-id="${selected.id}"`)}</div></header><div class="mail-body"><h2>${esc(selected.subject)}</h2>${selected.body.split('\n\n').map(p=>`<p>${esc(p).replaceAll('\n','<br>')}</p>`).join('')}${(selected.replies||[]).map(r=>`<div class="mail-saved-reply"><strong>You · demo sent</strong><p>${esc(r).replaceAll('\n','<br>')}</p></div>`).join('')}</div>${kitDemo.reply?`<form id="kit-reply" class="reply-editor" data-id="${selected.id}"><div class="reply-to">${kitAvatar(0)}<span>to ${esc(selected.name)}</span><button type="button" class="iconbtn" aria-label="Close reply" data-kit-action="close-reply">${icon('close')}</button></div><label><span class="visually-hidden">Reply message</span><textarea name="message" placeholder="Write your reply…" required></textarea></label><div class="inline-actions"><button class="btn primary" type="submit">Send Now</button><small>Demo message · saved locally</small></div></form>`:`<footer class="mail-footer">${kitButton('Add Note','email-note','medium',`data-id="${selected.id}"`)}<div class="inline-actions">${kitButton('Forward','forward','medium',`data-id="${selected.id}"`)}${kitButton('Reply','reply','primary medium',`data-id="${selected.id}"`)}</div></footer>`}`:`<div class="empty"><h2>No emails</h2><p>Try another folder, facility or search.</p></div>`;
 return `<div class="email-workspace ${kitDemo.mailMobile?'mail-detail-open':''}"><aside class="mail-list"><div class="mail-list-title"><h1>Manage Emails ✉️</h1>${isV2()?kitButton(`${icon('filter')}Filter`,'mail-filter'):''}</div>${underTabs([['all','All Mails'],['unread','Unread'],['archive','Archive']],kitDemo.mailFolder,'mail-folder')}${!isV2()?`<div class="v1-mail-filters">${kitSearch('emails','Search Email')}${kitButton(`${icon('filter')}Filter`,'mail-filter')}</div>`:''}<div class="mail-rows">${mails.map(m=>`<button type="button" class="mail-row ${selected?.id===m.id?'selected':''} ${!m.read?'unread':''}" data-kit-action="mail-open" data-id="${m.id}">${pageAsset(['37636.png','57de8.png','bc675.png','0d6f8.png'][m.avatar%4],undefined,32,'class="avatar-image"')}<div><div class="mail-from"><span>${esc(m.name)}</span><time>9.00 am</time></div><strong>${esc(m.subject)}</strong><p>${esc(m.body.split('\n\n')[1]||m.body)}</p></div></button>`).join('')||'<div class="empty">No matching messages.</div>'}</div></aside><section class="mail-detail" aria-label="Email details">${kitButton(`${icon('left')}Back to emails`,'mail-back','mail-back')}${detail}</section></div>`;
}
function taskDue(t){const key=t.due==='Late'?'late':t.due==='Safe'?'safe':'today';const files={late:['8a9dd.svg','de2ff.svg'],safe:['c1e45.svg','df82e.svg'],today:['1ad2a.svg','db478.svg']}[key];return `<span class="task-deadline due-${key}">${pageAsset(...files)}${key==='late'?'Due 4 days ago':key==='safe'?'Due Oct 14':'Due Today'}</span>`;}
function kitMore(kind,item){const open=kitDemo.menu===kind+'-'+item.id;return `<span class="page-menu-anchor"><button type="button" class="iconbtn" aria-label="Actions for ${esc(item.title||item.name)}" data-kit-action="menu" data-kind="${kind}" data-id="${item.id}" aria-expanded="${open}" aria-haspopup="menu">${kind==='note'&&!isV2()?pageAsset('75c72.svg'):pageIcon('more')}</button>${open?`<div class="page-menu" role="menu" aria-label="Actions for ${esc(item.title||item.name)}">${kind==='integration'?kitButton(`${pageIcon('info')}Details`,'integration-details','',`data-id="${item.id}" role="menuitem"`)+kitButton((item.on?'Turn off':'Turn on'),'integration-toggle','',`data-id="${item.id}" role="menuitem"`):kitButton(`${pageIcon('edit')}Edit`,'edit-'+kind,'',`data-id="${item.id}" role="menuitem"`)+kitButton(`${pageIcon('share')}Share`,'share-'+kind,'',`data-id="${item.id}" role="menuitem"`)}${kitButton(`${pageIcon('trash')}${kind==='integration'?'Remove':'Delete'}`,'delete-'+kind,'',`data-id="${item.id}" role="menuitem"`)}</div>`:''}</span>`;}
function taskCard(t){return `<article class="kit-task-card"><div class="card-top">${taskDue(t)}${kitMore('task',t)}</div><button class="task-title-button" data-kit-action="task-detail" data-id="${t.id}">${esc(t.title)}</button><footer><span>${companyIcon(t.facility)}${esc(['Sunrise Villa','Oak Terrace','Bayview'][t.facility])}</span><span>${kitAvatar(t.assigned,18)}${kitAvatar((t.assigned+1)%3,18)}</span></footer></article>`;}
function kitTasks(){
 const tasks=kitDemo.tasks.filter(t=>(kitDemo.taskGroup==='all'||t.group===kitDemo.taskGroup)&&(kitDemo.taskFacility==='all'||t.facility===Number(kitDemo.taskFacility))&&t.title.toLowerCase().includes(kitDemo.query.tasks.toLowerCase()));
 const groups=['Today','This Week','Upcoming','Completed'];
 const top=`<div class="tasks-viewbar">${underTabs([['list','List View'],['kanban','Kanban']],kitDemo.tasksView,'tasks-view')}<div class="inline-actions">${!isV2()?kitSearch('tasks','Search Tasks'):''}${kitButton(`${icon('upload')}Import/Export`,'task-export')}${kitButton(`${icon('filter')}Filter`,'task-filter')}</div></div>`;
 if(kitDemo.tasksView==='kanban')return top+`<div class="kanban-board">${groups.map(g=>`<section class="kanban-column"><header><h2>${g} <span>${tasks.filter(t=>t.group===g).length}</span></h2>${kitIconButton('Add task to '+g,'new-task','more',`data-group="${g}"`)}</header>${tasks.filter(t=>t.group===g).map(taskCard).join('')||'<p class="column-empty">No tasks</p>'}</section>`).join('')}</div>`;
 return top+`<div class="tablewrap tasks-table"><table><thead><tr><th>Task</th><th>Due Date</th><th>Related Record</th><th>Assigned To</th><th></th></tr></thead><tbody>${groups.map(g=>`<tr class="task-group"><th colspan="5">${g} <span>${tasks.filter(t=>t.group===g).length}</span></th></tr>${tasks.filter(t=>t.group===g).map(t=>`<tr><td><label class="task-complete"><input type="checkbox" data-kit-complete="${t.id}" aria-label="Complete ${esc(t.title)}" ${t.status==='Completed'?'checked':''}></label><button class="task-title-button" data-kit-action="task-detail" data-id="${t.id}">${esc(t.title)}</button></td><td>${taskDue(t)}</td><td><span class="related-facility">${companyIcon(t.facility)}${esc(['Sunrise Villa','Oak Terrace','Bayview'][t.facility])}</span></td><td><span class="assignee">${kitAvatar(t.assigned,18)}${['Jordan Davis','Casey Brooks','Sam Ellis'][t.assigned]}</span><span class="assignee">${kitAvatar((t.assigned+1)%3,18)}${['Jordan Davis','Casey Brooks','Sam Ellis'][(t.assigned+1)%3]}</span></td><td>${kitMore('task',t)}</td></tr>`).join('')}`).join('')}</tbody></table></div>`;
}
function kitNoteCard(n,share=false){return `<article class="kit-note-card" style="--note-color:${KIT_NOTE_COLORS[n.color]}"><div class="card-top">${isV2()?elevenIcon('audiobooks'):pageAsset('9626b.svg')}${share?'':kitMore('note',n)}</div><div class="note-card-copy"><button class="note-title-button" data-kit-action="note-detail" data-id="${n.id}">${esc(n.title)}</button><p>${esc(n.body).replaceAll('\n','<br>')}</p></div><footer>${pageAsset('dd03b.png',undefined,24,'class="avatar-image"')}<span>${esc(n.author)}</span><time>${n.day}</time></footer></article>`;}
function kitNotes(){const notes=kitDemo.notes.filter(n=>(n.title+' '+n.body).toLowerCase().includes(kitDemo.query.notes.toLowerCase()));return `<div class="notes-page"><h1>Keep Every Detail Close 📝</h1>${[true,false].map(f=>`<section><h2>${f?'Favorite Notes':'List Notes'}</h2><div class="notes-grid">${notes.filter(n=>n.favorite===f).map(n=>kitNoteCard(n)).join('')||'<p class="muted">No notes in this group.</p>'}</div></section>`).join('')}</div>`;}
function kitTaskEditor(id,group='Today'){
 const t=kitDemo.tasks.find(t=>t.id===id)||{id:0,title:'',group,facility:0,status:group==='Completed'?'Completed':'Todo',assigned:0,body:'',due:'Today',checklist:[false,false,false]};kitDemo.menu=null;
 modal(`<h2>${id?'Edit Task':'Create Task'}</h2><form id="kit-task-form" data-id="${t.id}"><div class="task-editor"><div class="inline-actions kit-compact-select"><label><span class="visually-hidden">Task group</span><select name="group">${['Today','This Week','Upcoming','Completed'].map(g=>`<option ${g===t.group?'selected':''}>${g}</option>`).join('')}</select></label>${taskStatus(t.status,t.status)}</div><label><span class="visually-hidden">Task name</span><input class="editor-title" name="title" placeholder="Untitled Task" value="${esc(t.title)}" required maxlength="140"></label><div class="task-editor-meta kit-compact-select"><label><span class="visually-hidden">Related facility</span><select name="facility">${['Sunrise Villa','Oak Terrace','Bayview'].map((n,i)=>`<option value="${i}" ${t.facility===i?'selected':''}>${n}</option>`).join('')}</select></label><label><span class="visually-hidden">Assign task</span><select name="assigned">${['Jordan Davis','Casey Brooks','Sam Ellis'].map((n,i)=>`<option value="${i}" ${t.assigned===i?'selected':''}>${n}</option>`).join('')}</select></label></div><label class="task-description"><span class="visually-hidden">Task description</span><textarea name="body" placeholder="Start typing your task details…">${esc(t.body)}</textarea></label>${kitButton('Use clinic preparation template','task-template')}<div class="task-checklist">${['Review resident matching','Confirm consent summary','Review staff decisions'].map((label,i)=>`<label class="checkline"><input type="checkbox" name="check-${i}" ${t.checklist[i]?'checked':''}>${label}</label>`).join('')}</div></div><div class="formfooter">${button('Cancel','close','ghost')}<button type="submit" class="btn primary">Save</button></div></form>`);$('#dialog').classList.add('kit-task-modal');
}
function kitTaskDetail(id){const t=kitDemo.tasks.find(t=>t.id===id);if(!t)return;kitDemo.menu=null;modal(`<h2>Task Details</h2><div class="task-editor">${taskDue(t)}<h3>${esc(t.title)}</h3><div class="inline-actions">${companyIcon(t.facility)}<span>${['Sunrise Villa','Oak Terrace','Bayview'][t.facility]}</span><span class="assignee">${kitAvatar(t.assigned,18)}${['Jordan Davis','Casey Brooks','Sam Ellis'][t.assigned]}</span>${taskStatus(t.status,t.status)}</div><p class="task-description">${esc(t.body).replaceAll('\n','<br>')}</p><div class="task-checklist">${['Review resident matching','Confirm consent summary','Review staff decisions'].map((label,i)=>`<label class="checkline"><input type="checkbox" data-kit-checklist="${t.id}" data-index="${i}" ${t.checklist[i]?'checked':''}>${label}</label>`).join('')}</div></div><div class="formfooter">${kitButton(`${pageIcon('share')}Share`,'share-task','',`data-id="${id}"`)}${kitButton(`${pageIcon('edit')}Edit Task`,'edit-task','primary',`data-id="${id}"`)}</div>`);$('#dialog').classList.add('kit-task-modal');}
function kitNoteEditor(id,initial={}){
 const n=kitDemo.notes.find(n=>n.id===id)||{id:0,title:'',body:'',color:'green',favorite:false,...initial};kitDemo.menu=null;
 modal(`<h2>${id?'Edit Note':'Create Note'}</h2><form id="kit-note-form" data-id="${n.id}"><div class="note-editor" style="--note-color:${KIT_NOTE_COLORS[n.color]}"><div class="note-editor-colors kit-compact-select"><label><span class="visually-hidden">Note color</span><select name="color" data-kit-note-color>${Object.keys(KIT_NOTE_COLORS).map(c=>`<option value="${c}" ${n.color===c?'selected':''}>${c[0].toUpperCase()+c.slice(1)}</option>`).join('')}</select></label></div><label><span class="visually-hidden">Note title</span><input class="editor-title" name="title" placeholder="Untitled Note" value="${esc(n.title)}" required maxlength="140"></label><label><span class="visually-hidden">Note content</span><textarea name="body" placeholder="Start typing your note…" required>${esc(n.body)}</textarea></label><label class="checkline"><input type="checkbox" name="favorite" ${n.favorite?'checked':''}> Add to Favorite Notes</label></div><div class="formfooter">${button('Cancel','close','ghost')}<button type="submit" class="btn primary">Save</button></div></form>`);$('#dialog').classList.add('kit-note-modal');$('#dialog').style.setProperty('--note-color',KIT_NOTE_COLORS[n.color]);
}
function kitNoteDetail(id){const n=kitDemo.notes.find(n=>n.id===id);if(!n)return;kitDemo.menu=null;modal(`<h2>Note Details</h2><div class="note-editor" style="--note-color:${KIT_NOTE_COLORS[n.color]}"><h3>${esc(n.title)}</h3><div class="note-detail-copy">${n.body.split('\n').map(p=>`<p>${esc(p)}</p>`).join('')}</div><small>${esc(n.author)} · ${n.day}</small></div><div class="formfooter"><div class="note-footer-start">${kitButton(`${pageIcon('trash')}Delete`,'delete-note','',`data-id="${id}"`)}</div>${kitButton(`${pageIcon('share')}Share`,'share-note','',`data-id="${id}"`)}${kitButton(`${pageIcon('edit')}Edit Note`,'edit-note','',`data-id="${id}"`)}</div>`);$('#dialog').classList.add('kit-note-modal');$('#dialog').style.setProperty('--note-color',KIT_NOTE_COLORS[n.color]);}
function kitCompose(mode='new',id=0){const m=kitDemo.emails.find(m=>m.id===id);const to=mode==='reply'?m?.email:'';const subject=mode==='new'?'':(mode==='forward'?'FW: ':'RE: ')+(m?.subject||'').replace(/^RE: /,'');modal(`<h2>New Messages</h2><form id="kit-compose" data-mode="${mode}" data-id="${id}"><div class="compose-layout"><div class="compose-content"><div class="compose-from"><span>From</span>${kitAvatar(0)}<strong>Jordan Davis</strong><small>jordan@example.test</small></div><label class="compose-to"><span>To</span><input name="to" type="email" aria-label="Recipient email" value="${esc(to)}" placeholder="recipient@example.test" required></label><label><span class="visually-hidden">Email subject</span><input class="compose-subject" name="subject" placeholder="Subject" value="${esc(subject)}" required></label><label><span class="visually-hidden">Email message</span><textarea name="message" placeholder="Write your message…" required>${mode==='forward'?esc(m?.body||''):''}</textarea></label></div><aside class="compose-recipients"><h3>Add Recipients</h3><p>This preview stores messages locally.</p>${kitDemo.members.slice(1).map((m,i)=>`<button type="button" data-kit-action="choose-recipient" data-email="${m.email}">${kitAvatar(i+1)}<span>${m.name}<small>${m.email}</small></span></button>`).join('')}</aside></div><div class="formfooter"><small class="demo-send-label">Demo message · no email is sent</small>${button('Cancel','close','ghost')}<button type="submit" class="btn primary">Send Now</button></div></form>`);$('#dialog').classList.add('kit-compose-modal');}
function kitFilter(kind){const fields=kind==='tasks'?`<label class="field"><span>Task group</span><select name="group">${['all','Today','This Week','Upcoming','Completed'].map(v=>`<option value="${v}" ${kitDemo.taskGroup===v?'selected':''}>${v==='all'?'All groups':v}</option>`).join('')}</select></label>`:'';modal(`<h2>Filter ${kind==='emails'?'Emails':'Tasks'}</h2><form id="kit-filter" data-kind="${kind}">${fields}<label class="field"><span>Facility</span><select name="facility"><option value="all">All facilities</option>${['Sunrise Villa','Oak Terrace','Bayview'].map((v,i)=>`<option value="${kind==='tasks'?i:v}" ${(kind==='tasks'?kitDemo.taskFacility:kitDemo.mailFacility)===String(kind==='tasks'?i:v)?'selected':''}>${v}</option>`).join('')}</select></label><div class="formfooter">${kitButton('Reset filter','kit-filter-reset')}<button class="btn primary" type="submit">Apply</button></div></form>`);$('#dialog').classList.add('kit-filter-modal');}
function kitShare(kind,id){const item=(kind==='note'?kitDemo.notes:kitDemo.tasks).find(x=>x.id===id);if(!item)return;kitDemo.menu=null;const url=location.origin+location.pathname+'#kit?view='+ (kind==='note'?'notes':'tasks')+'&item='+id;modal(`<h2>Share ${kind==='note'?'Note':'Task'}</h2><div class="kit-share-body">${kind==='note'?kitNoteCard(item,true):`<form id="kit-invite-task" data-id="${id}" class="share-invite"><label><span class="visually-hidden">Invite email</span><input name="email" type="email" placeholder="Email address" required></label><button type="submit" class="btn primary">Invite</button></form><h3>Who has access</h3><div class="share-access">Only those invited · demo</div><div class="share-people">${kitAvatar(0)}${kitAvatar(1)}<span>${2+(item.invited?.length||0)} people invited in this demo</span></div>`}<h3>Share link via</h3><div class="share-social">${['Facebook','X','WhatsApp','Telegram','Instagram'].map((name,i)=>kitButton(pageAsset(['a4acb.svg','c6434.svg','ec0fb.svg','7c431.svg','c0c2e.svg'][i]),'share-preview','',`aria-label="Preview ${name} sharing" data-platform="${name}"`)).join('')}</div>${kitButton(`${pageIcon('copy')}Copy Link`,'copy-link','',`data-link="${esc(url)}"`)}<small class="share-demo">Local demo link · available while this preview is open.</small></div>`);$('#dialog').classList.add('kit-share-modal');}
const KIT_SETTINGS=[['profile','Profile'],['calendar','Email & Calendar'],['storage','Storage'],['refer','Refer Team'],['notification','Notification'],['workspace','Workspace'],['members','Members'],['plans','Plans'],['integration','Integration']];
function miniToggle(label,value,action,extra=''){return `<button type="button" class="theme-switch mini-toggle" role="switch" aria-label="${esc(label)}" aria-checked="${value}" data-kit-action="${action}" ${extra}><span class="theme-track"><span></span></span></button>`;}
function settingsNotice(copy){return `<div class="settings-notice">${pageIcon('info')}<p>${copy}</p></div>`;}
function kitSettings(){return `<div class="kit-settings-layout"><aside class="kit-settings-nav" aria-label="Settings menu"><span class="navlabel">Settings Menu</span>${KIT_SETTINGS.map(([id,label])=>kitButton(`${pageIcon(id)}${label}`,'settings-tab',kitDemo.settings===id?'active':'',`data-value="${id}" aria-pressed="${kitDemo.settings===id}"`)).join('')}</aside><section class="kit-settings-content">${({profile:kitProfile,calendar:kitCalendar,storage:kitStorage,refer:kitRefer,notification:kitNotifications,workspace:kitWorkspace,members:kitMembers,plans:kitPlans,integration:kitIntegrations})[kitDemo.settings]()}</section></div>`;}
function kitWorkspaceMark(){return `<span class="workspace-mark" role="img" aria-label="Workspace picture"><span class="workspace-pattern"><span>${pageAsset('bcc35.svg')}</span></span><span class="workspace-user">${pageAsset('d7b66.svg')}</span></span>`;}
function profilePicture(type='profile'){const workspace=type==='workspace',asset=workspace?kitDemo.workspaceAvatar:kitDemo.avatar,removed=workspace?kitDemo.workspaceAvatarRemoved:kitDemo.avatarRemoved;return `<div class="profile-picture">${removed?'<span class="avatar-placeholder">'+(workspace?'ENT':'JD')+'</span>':workspace&&!asset?(isV2()?'<span class="avatar-placeholder">ENT</span>':kitWorkspaceMark()):`<img class="avatar-image" src="${asset||'assets/cliently/pages/3af20.png'}" width="64" height="64" alt="${workspace?'Workspace':'Profile'} picture">`}<div><h3>${workspace?'Workspace':'Profile'} Picture</h3><div class="inline-actions"><label class="btn solid">${icon('upload')}Upload New<input type="file" class="visually-hidden" accept="image/png,image/jpeg" data-kit-avatar="${type}" aria-label="Choose ${type} picture"></label>${kitButton('Remove','remove-avatar','',`data-type="${type}"`)}</div><small>PNG or JPG files up to 5mb. Local preview only.</small></div></div>`;}
function kitProfile(){const p=kitDemo.profileDraft||kitDemo.profile;return `<h1>Profile Settings</h1>${settingsNotice('Changes to this demo profile apply to the UI Kit previews.')}<form id="kit-profile-form" class="settings-form">${profilePicture()}<div class="formgrid">${field('First Name','first',p.first,'text','required')}${field('Last Name','last',p.last,'text','required')}</div><label class="field"><span>Phone Number</span><div class="phone-field"><span>${pageAsset('1f333.svg')}${icon('dropdown')}</span><input name="phone" type="tel" value="${esc(p.phone)}"></div></label>${field('Email Address','email',p.email,'email','required')}<div class="formgrid"><label class="field"><span>Preferred Timezone</span><select name="timezone">${['UTC + 7','UTC + 0','UTC - 5','UTC - 8'].map(v=>`<option ${v===p.timezone?'selected':''}>${v}</option>`).join('')}</select></label><label class="field"><span>Start Week on</span><select name="week">${['Monday','Sunday'].map(v=>`<option ${v===p.week?'selected':''}>${v}</option>`).join('')}</select></label></div></form>`;}
function connectButtons(items){return `<div class="inline-actions connection-buttons">${items.map(([name,asset])=>kitButton(`${pageAsset(asset)}${kitDemo.connections[name]?'Connected · ':''}${name}`,'connect-demo','',`data-provider="${name}"`)).join('')}</div>`;}
function kitCalendar(){return `<h1>Email & Calendar Settings</h1><p class="settings-description">Connect multiple accounts and manage their sharing settings independently. ${kitButton('Learn more','settings-help','text-link')}</p>${connectButtons([['Google Account','19720.svg'],['Microsoft Account','dadcd.svg']])}<section><h2>Forwarding Address</h2><div class="forwarding-address">${pageAsset('75dac.png',undefined,40)}<div><small>Email Address</small><strong>ent-demo@example.test</strong></div><span class="sync-state">${pageAsset('903d7.svg')} In Sync</span></div><p class="settings-description">Demo connections do not access an external account.</p></section><div class="settings-switch-row"><div><h2>Email Watermark</h2><p>Automatically add “Sent with ENT Care” to demo emails.</p></div>${miniToggle('Email Watermark',kitDemo.watermark,'watermark')}</div>`;}
function kitStorage(){return `<h1>Storage Settings</h1><p class="settings-description">Learn more about ${kitButton('Storage Integration','settings-help','text-link')}</p><section><h2>Connect File Storage</h2><p class="settings-description">You can connect multiple storage accounts in this preview.</p>${connectButtons([['Dropbox','97a7e.svg'],['Google Drive','ff428.svg'],['Microsoft OneDrive','20fbf.svg']])}</section>`;}
function kitNotifications(){const descriptions={Mentions:'Notify me when someone cites me with an @mention in notes or comments.',Replies:'Notify me when someone replies to my comments.','Email Grants':'Notify me when a demo email access request is accepted or denied.','Task Assignments':"Notify me when I'm assigned a task.",'Shared Resources':'Notify me when someone shares a resource with me.'};return `<h1>Notification</h1><p class="settings-description">Configure email and mobile app notifications.</p><div class="notification-settings">${Object.entries(kitDemo.notifications).map(([label,value])=>`<div class="settings-switch-row"><div><h2>${label}</h2><p>${descriptions[label]}</p></div>${miniToggle(label,value,'notification',`data-name="${label}"`)}</div>`).join('')}</div>`;}
function kitWorkspace(){const w=kitDemo.workspaceDraft||kitDemo.workspace;return `<h1>Workspace Settings</h1>${settingsNotice('Changes apply to this demo workspace only.')}<form id="kit-workspace-form" class="settings-form">${profilePicture('workspace')}${field('Workspace Name','name',w.name,'text','required')}${field('Workspace mail Address','email',w.email,'email','required')}<div class="formgrid"><label class="field"><span>Industry</span><select name="industry">${['Healthcare','Software as a Service (SaaS)','Professional Services'].map(v=>`<option ${v===w.industry?'selected':''}>${v}</option>`).join('')}</select></label><label class="field"><span>Currency</span><select name="currency">${['USD ($)','VND (₫)','EUR (€)'].map(v=>`<option ${v===w.currency?'selected':''}>${v}</option>`).join('')}</select></label></div></form><div class="settings-switch-row"><div><h2>Export Workspace Data</h2><p>Download tasks and notes as a JSON demo snapshot.</p></div>${kitButton(`${icon('upload')}Start Export`,'workspace-export')}</div><div class="danger-zone"><div><h2>Danger Zone</h2><p>Reset the UI Kit workspace to its sample values.</p></div>${kitButton('Reset Demo Workspace','workspace-reset','danger')}</div>`;}
function kitMembers(){return `<h1>Members</h1><p class="settings-description">Manage the people in your demo care workspace.</p>${kitButton(`${icon('plus')}Invite member`,'invite-member','primary')}<div class="tablewrap"><table><thead><tr><th>Member</th><th>Role</th><th></th></tr></thead><tbody>${kitDemo.members.map((m,i)=>`<tr><td><div class="identity-cell">${kitAvatar(i,32)}<div><strong>${esc(m.name)}</strong><small>${esc(m.email)}</small></div></div></td><td>${badge(m.role)}</td><td>${i?kitButton('Edit role','member-role','',`data-id="${m.id}"`):badge('You')}</td></tr>`).join('')}</tbody></table></div>`;}
function kitRefer(){return `<h1>Refer Teams</h1><div class="referral-panel"><div class="referral-head">${pageAsset('75dac.png',undefined,32)}<strong>Your referrals</strong><small>0/180 points earned · demo</small></div><div class="referral-progress">${Array.from({length:12},()=>'<span></span>').join('')}</div><div class="section-title"><h2>Rewards</h2>${kitButton(`${icon('arrow')}Learn More`,'referral-info')}</div><p class="settings-description">Preview the reward cards from Cliently.</p><div class="reward-grid">${[['0270c.png','Shirt'],['d01bb.png','Camera'],['e3bc2.png','Sounds'],['f9e45.png','Monitor']].map(([asset,label],i)=>`<article><img src="assets/cliently/pages/${asset}" alt="${label}" loading="lazy"><small>Tier 1</small><strong>Cliently Merch ${label}</strong><footer>${i%2?'10.000':'10'} Points</footer></article>`).join('')}</div></div><section><h2>Invite your team to the demo</h2><label class="field"><span>Your referral code</span><input value="ENT-DEMO" readonly></label>${kitButton(`${pageIcon('copy')}Copy Link`,'copy-link','',`data-link="${esc(location.origin+location.pathname+'#kit?view=settings')}"`)}</section>`;}
function kitPlans(){return `<h1>Plans</h1><p class="settings-description">View the Cliently plan layout. Plan changes are local previews.</p>${settingsNotice('Demo plan preview · no billing or purchase is performed.')}<div class="section-title"><h2>Pricing Plans</h2><div class="inline-actions"><span>Annually</span>${miniToggle('Monthly billing preview',kitDemo.monthly,'billing-cycle')}<span>Monthly</span></div></div><div class="plan-grid">${[['Plus Plan','$34','purple',['Enhanced email sending','Permission settings','Upgraded contact analysis']],['Pro Plan','$69','green',['Full access permissions','Advanced data enrichment','Priority support']],['Enterprise Plan','$119','blue',['Unlimited reporting','SAML and SSO','Custom billing']]].map(([name,price,color,features])=>`<article style="--note-color:${KIT_NOTE_COLORS[color]}"><header><span class="plan-icon">${pageAsset(name==='Pro Plan'?'8cb82.svg':name==='Plus Plan'?'9a4c7.svg':'9a4c7.svg')}</span><h3>${name}</h3><strong>${price}</strong><small>per user/month, billed ${kitDemo.monthly?'monthly':'annually'}</small></header><p>${name==='Plus Plan'?'For growing teams':name==='Pro Plan'?'For scaling businesses':'For large organizations'}</p>${features.map(f=>`<p class="plan-feature">${pageAsset('ca884.svg')} ${f}</p>`).join('')}${kitButton(kitDemo.plan===name?'Current plan':'Preview '+name,'plan-preview',kitDemo.plan===name?'':'primary',`data-value="${name}" ${kitDemo.plan===name?'disabled':''}`)}</article>`).join('')}</div><h2>Transaction History</h2><div class="tablewrap"><table><thead><tr><th>Pricing Type</th><th>Date & Time</th><th>Status</th></tr></thead><tbody><tr><td>Plus Plan · sample</td><td>Oct 1, 2026</td><td>Success</td></tr><tr><td>Pro Plan · sample</td><td>Sep 1, 2026</td><td>Success</td></tr></tbody></table></div>`;}
function integrationLogo(item){const bitmap=item.asset.endsWith('.png');if(bitmap)return `<span class="integration-logo logo-${item.id}"><img src="assets/cliently/pages/${item.asset}" alt="" loading="lazy"></span>`;return `<span class="integration-logo">${pageAsset(item.asset)}</span>`;}
function kitIntegrations(){const items=kitDemo.integrations.filter(i=>!i.removed&&(kitDemo.integrationFilter==='all'||i.on)&&(i.name+' '+i.category).toLowerCase().includes(kitDemo.query.integration.toLowerCase()));return `<h1>Integrations</h1><p class="settings-description">Connect your workspace to other tools. Connections are simulated.</p><h2>Discover Integrations</h2><div class="integration-search">${kitSearch('integration','Search integration here…')}${kitButton(`${icon('filter')}${kitDemo.integrationFilter==='all'?'Filter':'Connected'}`,'integration-filter')}</div><div class="integration-grid">${items.map(i=>`<article>${integrationLogo(i)}<div><strong>${i.name}</strong><small>${i.category}${i.on?' · Connected':''}</small></div>${kitMore('integration',i)}</article>`).join('')||'<p>No matching integrations.</p>'}</div>`;}
const KIT_TOPICS=[
 {id:'started',title:'Getting Started',copy:'Set up your workspace, review facilities, and prepare the census workflow.',link:'Read Guide',asset:'21146.svg',color:'#FFE176'},
 {id:'census',title:'Census & Intake',copy:'Learn to review matches, compare source documents, and confirm staff decisions.',link:'Review Workflows',asset:'8c6d6.svg',color:'#958CFB'},
 {id:'workspace',title:'Workspace Settings',copy:'Manage your profile, team members, and notification preferences.',link:'View Settings Help',asset:'d67d3.svg',color:'#BAF076'},
 {id:'integrations',title:'Integrations',copy:'Explore email, calendar, storage and integration settings in the demo.',link:'View Integrations',asset:'adc6a.svg',color:'#97BEFB'}
];
const KIT_FAQS=[
 ['How do I set up my care workspace?','Open Settings to review your profile and workspace. Use Facilities to review each sample facility and its consent summary.'],
 ['How do I resolve a possible patient match?','Open Census audit and select Review. Compare the resident and sample candidate, then confirm the matching decision before using visit history.'],
 ['Where can I export the census report?','Use Export report on Census audit. Choose the current filtered view, all residents, or Schedule / Courtesy decisions.'],
 ['What happens when an attachment fails?','The saved patient ID is retained. Retry attachment uses that same patient instead of creating a second record.'],
 ['Does this prototype send emails?','No. Send Now saves a fictional message in this local UI Kit preview. No email is sent to another person.'],
 ['Can I import a census document?','The census demo can select a local PDF or image; extraction uses the fictional sample. No document is uploaded.'],
 ['Is there a mobile version?','These previews adapt to smaller screens. Wide tables scroll inside their container and the navigation uses a drawer.'],
 ['Are demo changes permanent?','Changes remain in the current page session. Reload restores sample data; the Light/Dark preference is retained.']
];
function kitHelp(){if(kitDemo.article)return kitHelpArticle(kitDemo.article);const query=kitDemo.query.help.toLowerCase();const topics=KIT_TOPICS.filter(t=>(t.title+' '+t.copy).toLowerCase().includes(query));const faqs=KIT_FAQS.map(([q,a],i)=>({q,a,i})).filter(f=>(f.q+' '+f.a).toLowerCase().includes(query));return `<div class="help-page"><header class="help-hero"><h1>How can we help you succeed?</h1><p>Find answers, get step-by-step guides, or contact our support team.</p><label class="help-search"><span class="visually-hidden">Search help</span><input data-kit-search="help" placeholder="Type your question or keyword…" value="${esc(kitDemo.query.help)}">${icon('search')}</label></header><section><div class="section-title"><h2>Popular Help Topics</h2>${kitButton('See more','help-more','text-link')}</div><div class="help-topics">${topics.map(t=>`<article><span class="help-topic-icon" style="background:${t.color}">${isV2()?elevenIcon(t.id==='started'?'home':t.id==='census'?'file':t.id==='workspace'?'profile':'integration'):pageAsset(t.asset)}</span><h3>${t.title}</h3><p>${t.copy}</p>${kitButton(t.link+' →','help-topic','text-link',`data-value="${t.id}"`)}</article>`).join('')||'<p>No matching topics.</p>'}</div>${kitDemo.moreHelp?'<p class="help-more-copy">Additional guides: matching decisions, attachment retry, consent progress and clinic scheduling. Choose a topic or search above.</p>':''}</section><section><div class="section-title"><h2>Frequently Asked Question</h2>${kitButton('See more','help-more','text-link')}</div><div class="faq-grid">${[0,1].map(column=>`<div>${faqs.filter((_,i)=>i%2===column).map(f=>`<article class="faq-item ${kitDemo.faq===f.i?'open':''}"><button data-kit-action="faq" data-id="${f.i}" aria-expanded="${kitDemo.faq===f.i}">${f.q}<span aria-hidden="true">${isV2()?`<span class="v2-faq-chevron ${kitDemo.faq===f.i?'open':''}">${elevenIcon('theme')}</span>`:pageAsset(kitDemo.faq===f.i?'6e602.svg':'1e99a.svg')}</span></button>${kitDemo.faq===f.i?`<p>${f.a}</p>`:''}</article>`).join('')}</div>`).join('')}</div></section><section><h2>Contact Support</h2><div class="contact-grid">${[['Live Chat','Mon–Fri 9:00 AM – 6:00 PM','chat','chat'],['Email Address','support@example.test','email','email'],['Phone Number','+1 (202) 555-0100','phone','phone']].map(([label,value,asset,kind])=>`<button data-kit-action="support" data-value="${kind}"><span><small>${label}</small><strong>${value}</strong></span>${`<span class="contact-icon">${pageIcon(asset)}</span>`}</button>`).join('')}</div></section></div>`;}
function kitHelpArticle(id){const t=KIT_TOPICS.find(t=>t.id===id)||KIT_TOPICS[0];const sections=[['Review your workspace','Use Settings to update your fictional profile and workspace, then save changes in this demo.'],['Prepare facility records','Review the consent summary and resident list for each facility before planning a clinic.'],['Review census and intake','Confirm matching decisions and compare extracted information with the source document.'],['Track work with Tasks and Notes','Create a task, assign a coordinator and mark the work complete. Add a note to keep preparation details together.'],['Understand demo integrations','Email, storage and integration connections are simulated. No external account is connected or changed.']];return `<div class="help-article-page"><div class="help-article-main">${kitButton(`${icon('left')}Help & Center / Topics`,'help-back','text-link')}<h1>${t.title}</h1><p>${t.copy}</p><img class="help-article-cover" src="assets/cliently/pages/ea216.png" alt="Tablet and keyboard on a desk"><div>${sections.map(([title,copy],i)=>`<section id="help-section-${i}"><h2>${i+1}. ${title}</h2><p>${copy}</p>${i===2?'<a href="#census">Go to Census audit →</a>':i===3?'<a href="#kit?view=tasks">Go to Tasks →</a>':''}</section>`).join('')}</div></div><aside class="help-contents"><h2>On This Page</h2>${sections.map(([title],i)=>kitButton(`${i+1}. ${title}`,'help-scroll','text-link',`data-id="${i}"`)).join('')}${kitButton('Need Help?','support','text-link','data-value="email"')}</aside></div>`;}
function kitDownload(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function openKitLinkedItem(){if(screen.route!=='kit')return;const params=new URLSearchParams(location.hash.split('?')[1]||'');const id=Number(params.get('item'));const key=kitView()+'-'+id;if(!id||kitDemo.linkedKey===key)return;kitDemo.linkedKey=key;if(kitView()==='notes')kitNoteDetail(id);if(kitView()==='tasks')kitTaskDetail(id);}
function saveKitSettings(){const f=$('#kit-profile-form')||$('#kit-workspace-form');if(f){if(!f.reportValidity())return;const data=Object.fromEntries(new FormData(f));if(f.id==='kit-profile-form'){kitDemo.profile=data;kitDemo.profileDraft=null;}else{kitDemo.workspace=data;kitDemo.workspaceDraft=null;}}toast('Settings saved in this demo session.');}
function deleteKitItem(kind,id){const item=(kind==='note'?kitDemo.notes:kind==='task'?kitDemo.tasks:kitDemo.integrations).find(x=>x.id===id);if(!item)return;modal(`<h2>${kind==='integration'?'Remove integration':'Delete '+kind}?</h2><p>${esc(item.title||item.name)}</p><p>This changes only the demo preview. Reload restores the original sample.</p><div class="formfooter">${button('Cancel','close','ghost')}${kitButton('Delete','confirm-delete','danger',`data-kind="${kind}" data-id="${id}"`)}</div>`);}
document.addEventListener('click',async e=>{
 const b=e.target.closest('[data-kit-action]');if(!b)return;const action=b.dataset.kitAction,id=Number(b.dataset.id),v=b.dataset.value;
 switch(action){
  case 'mail-folder':kitDemo.mailFolder=v;kitDemo.reply=false;kitDemo.mailMobile=false;render();break;
  case 'mail-open':kitDemo.mailSelected=id;kitDemo.emails.find(m=>m.id===id).read=true;kitDemo.mailMobile=true;kitDemo.reply=false;render();break;
  case 'mail-back':kitDemo.mailMobile=false;render();break;
  case 'mail-read':{const m=kitDemo.emails.find(m=>m.id===id);m.read=!m.read;render();break;}
  case 'mail-archive':{const m=kitDemo.emails.find(m=>m.id===id);m.archive=!m.archive;kitDemo.reply=false;render();toast(m.archive?'Email archived in demo.':'Email restored.');break;}
  case 'compose':kitCompose();break;
  case 'forward':kitCompose('forward',id);break;
  case 'choose-recipient':$('#kit-compose [name="to"]').value=b.dataset.email;break;
  case 'reply':kitDemo.mailSelected=id;kitDemo.reply=true;render();$('#kit-reply textarea').focus();break;
  case 'close-reply':kitDemo.reply=false;render();break;
  case 'email-note':{const m=kitDemo.emails.find(m=>m.id===id);kitNoteEditor(0,{title:m.subject,body:m.body});break;}
  case 'mail-filter':kitFilter('emails');break;
  case 'tasks-view':kitDemo.tasksView=v;kitDemo.menu=null;render();break;
  case 'new-task':kitTaskEditor(0,b.dataset.group||'Today');break;
  case 'edit-task':kitTaskEditor(id);break;
  case 'task-detail':kitTaskDetail(id);break;
  case 'task-filter':kitFilter('tasks');break;
  case 'kit-filter-reset':$('#kit-filter').querySelectorAll('select').forEach(s=>{s.value='all';s.dispatchEvent(new Event('select-sync'));});break;
  case 'task-template':$('#kit-task-form [name="title"]').value='Prepare the next ENT clinic';$('#kit-task-form [name="body"]').value='Review the census, confirm resident matching, and prepare the consent summary for the facility.';break;
  case 'task-export':modal(`<h2>Import / Export Tasks</h2><p>Export your demo task list or import a JSON task snapshot.</p><div class="inline-actions">${kitButton('Export JSON','task-download','primary')}<label class="btn">Import JSON<input type="file" accept=".json,application/json" class="visually-hidden" data-kit-import aria-label="Import task JSON"></label></div><p class="settings-description">Files are read locally and are not uploaded.</p>`);break;
  case 'task-download':kitDownload('ent-demo-tasks.json',JSON.stringify(kitDemo.tasks,null,2));toast('Demo task snapshot exported.');break;
  case 'new-note':kitNoteEditor(0);break;
  case 'edit-note':kitNoteEditor(id);break;
  case 'note-detail':kitNoteDetail(id);break;
  case 'menu':kitDemo.menu=kitDemo.menu===b.dataset.kind+'-'+id?null:b.dataset.kind+'-'+id;render();requestAnimationFrame(()=>$('.page-menu [role="menuitem"]')?.focus());break;
  case 'delete-note':case 'delete-task':case 'delete-integration':deleteKitItem(action.slice(7),id);break;
  case 'confirm-delete':if(b.dataset.kind==='integration')kitDemo.integrations.find(i=>i.id===id).removed=true;else kitDemo[b.dataset.kind==='note'?'notes':'tasks']=kitDemo[b.dataset.kind==='note'?'notes':'tasks'].filter(i=>i.id!==id);kitDemo.menu=null;closeModal();render();toast('Removed from the local demo.');break;
  case 'share-note':kitShare('note',id);break;
  case 'share-task':kitShare('task',id);break;
  case 'share-preview':toast(b.dataset.platform+' sharing preview. Use Copy Link to share the local demo URL.');break;
  case 'copy-link':try{await navigator.clipboard.writeText(b.dataset.link);toast('Demo link copied.');}catch{modal(`<h2>Demo Link</h2><label class="field"><span>Copy this link</span><input readonly value="${esc(b.dataset.link)}"></label>`);}break;
  case 'settings-tab':kitDemo.settings=v;kitDemo.menu=null;render();break;
  case 'settings-save':saveKitSettings();break;
  case 'settings-default':kitDemo.profileDraft=null;kitDemo.workspaceDraft=null;kitDemo.profile={first:'Jordan',last:'Davis',phone:'+12025550100',email:'jordan@example.test',timezone:'UTC + 7',week:'Monday'};kitDemo.notifications=Object.fromEntries(Object.keys(kitDemo.notifications).map(k=>[k,true]));kitDemo.watermark=true;kitDemo.workspace={name:'ENT Care',email:'workspace@example.test',industry:'Healthcare',currency:'USD ($)'};render();toast('Default demo settings restored.');break;
  case 'notification':kitDemo.notifications[b.dataset.name]=!kitDemo.notifications[b.dataset.name];b.setAttribute('aria-checked',String(kitDemo.notifications[b.dataset.name]));break;
  case 'watermark':kitDemo.watermark=!kitDemo.watermark;b.setAttribute('aria-checked',String(kitDemo.watermark));break;
  case 'billing-cycle':kitDemo.monthly=!kitDemo.monthly;render();break;
  case 'remove-avatar':{const key=b.dataset.type==='workspace'?'workspaceAvatar':'avatar';kitDemo[key+'Removed']=true;if(kitDemo[key])URL.revokeObjectURL(kitDemo[key]);kitDemo[key]=null;render();break;}
  case 'connect-demo':kitDemo.connections[b.dataset.provider]=!kitDemo.connections[b.dataset.provider];render();toast((kitDemo.connections[b.dataset.provider]?'Connected ':'Disconnected ')+b.dataset.provider+' in demo only.');break;
  case 'settings-help':kitDemo.article=kitDemo.settings==='storage'?'integrations':'workspace';location.hash='kit?view=help';break;
  case 'workspace-export':kitDownload('ent-demo-workspace.json',JSON.stringify({workspace:kitDemo.workspace,tasks:kitDemo.tasks,notes:kitDemo.notes},null,2));toast('Demo workspace snapshot exported.');break;
  case 'workspace-reset':modal(`<h2>Reset demo workspace?</h2><p>This restores the UI Kit settings. Your ENT census and intake demo records remain available.</p><div class="formfooter">${button('Cancel','close','ghost')}${kitButton('Reset','confirm-workspace-reset','danger')}</div>`);break;
  case 'confirm-workspace-reset':kitDemo.workspace={name:'ENT Care',email:'workspace@example.test',industry:'Healthcare',currency:'USD ($)'};kitDemo.workspaceDraft=null;closeModal();render();toast('Demo workspace settings reset.');break;
  case 'invite-member':modal(`<h2>Invite member</h2><form id="kit-member-form">${field('Name','name','','text','required')}${field('Email address','email','','email','required')}<label class="field"><span>Role</span><select name="role"><option>Staff</option><option>Coordinator</option><option>Admin</option></select></label><p>Invitations are saved in this local demo. No email is sent.</p><div class="formfooter">${button('Cancel','close','ghost')}<button class="btn primary" type="submit">Invite</button></div></form>`);break;
  case 'member-role':{const m=kitDemo.members.find(m=>m.id===id);modal(`<h2>Edit role</h2><p>${esc(m.name)}</p><form id="kit-member-role" data-id="${id}"><label class="field"><span>Role</span><select name="role">${['Staff','Coordinator','Admin'].map(r=>`<option ${m.role===r?'selected':''}>${r}</option>`).join('')}</select></label><div class="formfooter">${button('Cancel','close','ghost')}<button class="btn primary" type="submit">Save</button></div></form>`);break;}
  case 'referral-info':modal(`<h2>Referral rewards preview</h2><p>These original Cliently reward cards demonstrate the Figma layout. Points and rewards are sample content; no reward is claimed.</p>${button('Close','close')}`);break;
  case 'plan-preview':kitDemo.plan=v;render();toast(v+' selected in demo. No purchase or billing change.');break;
  case 'integration-filter':kitDemo.integrationFilter=kitDemo.integrationFilter==='all'?'connected':'all';render();break;
  case 'integration-toggle':{const i=kitDemo.integrations.find(i=>i.id===id);i.on=!i.on;kitDemo.menu=null;if($('#dialog').open)closeModal();render();toast(i.name+' '+(i.on?'enabled':'disabled')+' in demo.');break;}
  case 'integration-details':{const i=kitDemo.integrations.find(i=>i.id===id);kitDemo.menu=null;modal(`<h2>${i.name}</h2><p>${i.category}</p><p>Preview this connection in your ENT workspace. No external credentials or data are accessed.</p><div class="formfooter">${kitButton(i.on?'Disconnect demo':'Connect demo','integration-toggle','primary',`data-id="${id}"`)}</div>`);break;}
  case 'faq':kitDemo.faq=kitDemo.faq===id?-1:id;render();break;
  case 'help-more':kitDemo.moreHelp=!kitDemo.moreHelp;render();break;
  case 'help-topic':kitDemo.article=v;render();window.scrollTo({top:0});break;
  case 'help-back':kitDemo.article=null;render();window.scrollTo({top:0});break;
  case 'help-scroll':$('#help-section-'+id)?.scrollIntoView({behavior:'smooth',block:'start'});break;
  case 'support':if(v==='email'){kitCompose();$('#kit-compose [name="to"]').value='support@example.test';$('#kit-compose [name="subject"]').value='Help with the ENT Care demo';}else modal(`<h2>${v==='chat'?'Support chat preview':'Phone support'}</h2><p>${v==='chat'?'Open a help topic or prepare a demo email to the care coordinator.':'Sample support number: +1 (202) 555-0100. No call is placed.'}</p>${kitButton('Prepare support email','support','primary','data-value="email"')}`);break;
 }
});
document.addEventListener('input',e=>{
 const kind=e.target.dataset.kitSearch;
 if(kind){kitDemo.query[kind]=e.target.value;const pos=e.target.selectionStart;render();const input=$('[data-kit-search="'+kind+'"]');input?.focus();input?.setSelectionRange(pos,pos);}
 const f=e.target.closest('#kit-profile-form,#kit-workspace-form');if(f){const data=Object.fromEntries(new FormData(f));kitDemo[f.id==='kit-profile-form'?'profileDraft':'workspaceDraft']=data;}
});
document.addEventListener('change',async e=>{
 const f=e.target.closest('#kit-profile-form,#kit-workspace-form');if(f)kitDemo[f.id==='kit-profile-form'?'profileDraft':'workspaceDraft']=Object.fromEntries(new FormData(f));
 const id=Number(e.target.dataset.kitComplete);if(id){const t=kitDemo.tasks.find(t=>t.id===id);if(e.target.checked){t.previousGroup=t.group;t.status='Completed';t.group='Completed';}else{t.status='Todo';t.group=t.previousGroup||'Today';}render();}
 if(e.target.hasAttribute('data-kit-checklist'))kitDemo.tasks.find(t=>t.id===Number(e.target.dataset.kitChecklist)).checklist[Number(e.target.dataset.index)]=e.target.checked;
 if(e.target.hasAttribute('data-kit-note-color')){$('#dialog').style.setProperty('--note-color',KIT_NOTE_COLORS[e.target.value]);$('.note-editor').style.setProperty('--note-color',KIT_NOTE_COLORS[e.target.value]);}
 if(e.target.hasAttribute('data-kit-avatar')){const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024||!['image/png','image/jpeg'].includes(file.type)){toast('Choose a PNG or JPG smaller than 5 MB.');return;}const key=e.target.dataset.kitAvatar==='workspace'?'workspaceAvatar':'avatar';if(kitDemo[key])URL.revokeObjectURL(kitDemo[key]);kitDemo[key]=URL.createObjectURL(file);kitDemo[key+'Removed']=false;render();toast('Picture preview updated locally.');}
 if(e.target.hasAttribute('data-kit-import')){try{const file=e.target.files[0];if(!file||file.size>1024*1024)throw Error('Choose a JSON snapshot smaller than 1 MB.');const data=JSON.parse(await file.text());if(!Array.isArray(data)||data.length>200)throw Error('Use an array of up to 200 tasks.');kitDemo.tasks=data.map((t,i)=>{if(!t||typeof t.title!=='string'||!t.title.trim())throw Error('Each task needs a title.');return {id:i+1,title:t.title.slice(0,140),group:['Today','This Week','Upcoming','Completed'].includes(t.group)?t.group:'Today',facility:[0,1,2].includes(t.facility)?t.facility:0,status:t.group==='Completed'?'Completed':['Todo','Inprogress','Review'].includes(t.status)?t.status:'Todo',due:['Today','Late','Safe'].includes(t.due)?t.due:'Today',assigned:[0,1,2].includes(t.assigned)?t.assigned:0,body:typeof t.body==='string'?t.body.slice(0,10000):'',checklist:[0,1,2].map(i=>Boolean(t.checklist?.[i]))};});closeModal();render();toast(data.length+' demo tasks imported locally.');}catch(err){toast(err.message);}}
});
document.addEventListener('submit',e=>{
 const f=e.target;if(!f.id.startsWith('kit-'))return;e.preventDefault();if(!f.reportValidity())return;const d=new FormData(f),id=Number(f.dataset.id);
 if(f.id==='kit-task-form'){const t=kitDemo.tasks.find(t=>t.id===id);const group=d.get('group');const data={title:String(d.get('title')).trim(),group,facility:Number(d.get('facility')),assigned:Number(d.get('assigned')),body:String(d.get('body')),status:group==='Completed'?'Completed':t?.status==='Completed'?'Todo':t?.status||'Todo',due:t?.due||'Today',checklist:[0,1,2].map(i=>d.has('check-'+i))};if(t)Object.assign(t,data);else kitDemo.tasks.push({id:Math.max(0,...kitDemo.tasks.map(t=>t.id))+1,...data});kitDemo.query.tasks='';kitDemo.taskGroup='all';kitDemo.taskFacility='all';closeModal();render();toast('Task saved in this demo.');}
 if(f.id==='kit-note-form'){const n=kitDemo.notes.find(n=>n.id===id);const data={title:String(d.get('title')).trim(),body:String(d.get('body')),color:d.get('color'),favorite:d.has('favorite'),author:kitDemo.profile.first+' '+kitDemo.profile.last,day:'Oct 7, 2026'};if(n)Object.assign(n,data);else kitDemo.notes.unshift({id:Math.max(0,...kitDemo.notes.map(n=>n.id))+1,...data});kitDemo.query.notes='';closeModal();render();toast('Note saved in this demo.');}
 if(f.id==='kit-compose'){const item={id:Math.max(...kitDemo.emails.map(m=>m.id))+1,name:'Jordan Davis · Sent',email:String(d.get('to')),subject:String(d.get('subject')),body:String(d.get('message')),read:true,archive:false,avatar:0,facility:'Sunrise Villa'};kitDemo.emails.unshift(item);kitDemo.mailSelected=item.id;kitDemo.mailFolder='all';kitDemo.mailFacility='all';kitDemo.query.emails='';closeModal();render();toast('Message saved locally. No email was sent.');}
 if(f.id==='kit-reply'){const m=kitDemo.emails.find(m=>m.id===id);(m.replies??=[]).push(String(d.get('message')));kitDemo.reply=false;render();toast('Reply saved locally. No email was sent.');}
 if(f.id==='kit-filter'){if(f.dataset.kind==='tasks'){kitDemo.taskGroup=d.get('group');kitDemo.taskFacility=d.get('facility');}else kitDemo.mailFacility=d.get('facility');closeModal();render();}
 if(f.id==='kit-member-form'){kitDemo.members.push({id:Math.max(...kitDemo.members.map(m=>m.id))+1,name:String(d.get('name')),email:String(d.get('email')),role:d.get('role')});closeModal();render();toast('Member added in demo. No invitation was sent.');}
 if(f.id==='kit-member-role'){kitDemo.members.find(m=>m.id===id).role=d.get('role');closeModal();render();toast('Demo role saved.');}
 if(f.id==='kit-invite-task'){const t=kitDemo.tasks.find(t=>t.id===id);(t.invited??=[]).push(String(d.get('email')));kitShare('task',id);toast('Invitation saved in demo. No email was sent.');}
});
function closeKitMenu(restoreFocus=false){const trigger=document.querySelector('.page-menu-anchor>[aria-expanded="true"]');kitDemo.menu=null;document.querySelectorAll('.page-menu-anchor .page-menu').forEach(m=>m.remove());trigger?.setAttribute('aria-expanded','false');if(restoreFocus)trigger?.focus();}
document.addEventListener('keydown',e=>{
 if(kitDemo.menu&&['Escape','Tab'].includes(e.key)){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();}closeKitMenu(true);return;}
 if(e.target.closest('.kit-page-tabs')&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('.kit-page-tabs a')],i=tabs.indexOf(e.target);const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].click();requestAnimationFrame(()=>document.querySelector('.kit-page-tabs [aria-selected="true"]')?.focus());}
 if(e.target.closest('.page-menu')&&['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const buttons=[...document.querySelectorAll('.page-menu [role="menuitem"]')],i=buttons.indexOf(e.target);const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus();}
});
document.addEventListener('pointerdown',e=>{if(kitDemo.menu&&!e.target.closest('.page-menu-anchor'))closeKitMenu();});

function positionKitMenu(){const menu=$('.page-menu-anchor .page-menu');if(!menu)return;const anchor=menu.parentElement.getBoundingClientRect(),box=menu.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(innerWidth-box.width-8,anchor.right-box.width))+'px';menu.style.top=(anchor.bottom+box.height+8<innerHeight?anchor.bottom+4:Math.max(8,anchor.top-box.height-4))+'px';}
window.addEventListener('resize',positionKitMenu);document.addEventListener('scroll',positionKitMenu,true);
