const {test}=require('node:test');
const assert=require('node:assert/strict');
const {CareStore}=require('../care-model.js');
function memory(){const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};}
function fixture(){const storage=memory();const store=new CareStore(storage,storage,()=>new Date('2026-10-08T04:00:00Z'));store.login('admin','demo1234');return {store,storage};}
test('engineer fixture: four facilities, 62 residents, one ready and one scheduled',()=>{const {store}=fixture();assert.equal(store.db.facilities.length,4);assert.equal(store.db.residents.length,62);assert.deepEqual(store.db.facilities.map(f=>store.summary(f).signed),[14,17,11,0]);assert.equal(store.summary(store.db.facilities[1]).status,'Ready to schedule');assert.equal(store.summary(store.db.facilities[2]).status,'Scheduled');});
test('staff sees only assigned residents and cannot mutate admin data',()=>{const {store}=fixture();store.login('staff','demo1234');assert.equal(store.visibleResidents().length,24);assert.throws(()=>store.resident('res-r25'),/unavailable/);assert.throws(()=>store.updateThreshold('f1',10),/admin/);assert.throws(()=>store.accountStatus('u-tbrooks',false),/admin/);assert.throws(()=>store.schedule('f1','2026-10-21'),/admin/);});
test('bad credentials, deactivated and platform accounts cannot create sessions',()=>{const {store}=fixture();store.logout();for(const username of ['locked','platform'])assert.throws(()=>store.login(username,'demo1234'));assert.throws(()=>store.login('admin','wrong'));assert.equal(store.user(),null);});
test('partial delivery records each channel, both failures preserve unsigned state',()=>{const {store}=fixture();const r=store.saveResident({facilityId:'f1',name:'Demo Contact',dob:'1940-01-01',room:'301',signer:'POA',rep:{name:'Demo Representative',email:'bounce@example.test',phone:'+14155550123'}});let results=store.send(r.id);assert.deepEqual(results.map(d=>d.status),['Failed','Delivered']);assert.equal(r.status,'Sent');r.rep.phone='+14155550000';r.status='Pending';results=store.send(r.id);assert(results.every(d=>d.status==='Failed'));assert.equal(r.status,'Pending');r.rep.email='fixed@example.test';store.send(r.id,'EMAIL');assert.equal(r.deliveries.find(d=>d.channel==='EMAIL').status,'Delivered');assert.equal(r.deliveries.find(d=>d.channel==='SMS').status,'Failed');});
test('one new signature triggers exactly one PCC scheduling alert',()=>{const {store}=fixture(),r=store.db.residents.find(r=>r.facilityId==='f1'&&r.status==='Pending'),payload={accepted:true,signerName:r.name,relationship:'Self',signature:[{text:r.name}]};store.sign(r.token,payload);store.sign(r.token,payload);const alerts=store.db.messages.filter(m=>m.facilityId==='f1'&&m.purpose==='Alert');assert.equal(alerts.length,1);assert.equal(store.summary(store.db.facilities[0]).ready,15);});
test('replace link invalidates old public URL, including an already opened link',()=>{const {store}=fixture(),r=store.db.residents.find(r=>r.status==='Pending'),old=r.token;store.replaceLink(r.id);assert.equal(store.signing(old),undefined);assert.throws(()=>store.sign(old,{accepted:true,signature:[{text:'Demo'}],signerName:'Demo',relationship:'Self'}),/invalid/);});
test('empty signature and missing certification cannot change consent',()=>{const {store}=fixture(),r=store.db.residents.find(r=>r.status==='Pending');assert.throws(()=>store.sign(r.token,{accepted:false,signature:[{text:'Demo'}],signerName:'Demo',relationship:'Self'}));assert.throws(()=>store.sign(r.token,{accepted:true,signature:[],signerName:'Demo',relationship:'Self'}));assert.equal(r.status,'Pending');});
test('do not contact blocks requests/reminders and can be reversed',()=>{const {store}=fixture(),r=store.db.residents.find(r=>r.status==='Sent');store.doNotContact(r.id,true);assert.throws(()=>store.send(r.id),/do not contact/);store.doNotContact(r.id,false);assert.equal(r.status,'Sent');});
test('PDF failure preserves the signed consent; retry does not sign again',()=>{const {store}=fixture(),r=store.db.residents.find(r=>r.status==='Signed'&&!r.pdf),at=r.signedAt;store.retryPDF(r.id);assert.equal(r.pdf,true);assert.equal(r.signedAt,at);assert.equal(r.status,'Signed');});
test('scheduled clinic locks threshold; new signatures join booked date',()=>{const {store}=fixture();const n=store.schedule('f2','2026-10-22');assert.equal(n,17);assert.throws(()=>store.updateThreshold('f2',12),/locked/);const r=store.db.residents.find(r=>r.facilityId==='f2'&&r.status==='Pending');store.sign(r.token,{accepted:true,signature:[{text:r.name}],signerName:r.name,relationship:'Self'});assert.equal(r.visitDate,'2026-10-22');assert.equal(store.schedule('f2','2026-10-23',true),18);assert.equal(store.db.facilities[1].alertAt,null);});
test('expired clinic archives consent and rotates token for a new round',()=>{const {store}=fixture();store.schedule('f2','2026-10-09');const r=store.db.residents.find(r=>r.facilityId==='f2'&&r.visitDate),old=r.token;store.db.offset=3;store.rollCycles();assert.equal(r.status,'Pending');assert.equal(r.archives.length,1);assert.notEqual(r.token,old);assert.equal(store.summary(store.db.facilities[1]).ready,0);assert.equal(store.signing(old),undefined);});
test('save and reload preserve new residents and signatures in both editions',()=>{const {store,storage}=fixture(),r=store.saveResident({facilityId:'f1',name:'Persistence Demo',dob:'1940-02-02',room:'202',signer:'Self'});store.sign(r.token,{accepted:true,signature:[{text:r.name}],signerName:r.name,relationship:'Self'});const restored=new CareStore(storage,storage,()=>new Date('2026-10-08T04:00:00Z'));assert.equal(restored.resident(r.id).status,'Signed');assert.deepEqual(restored.resident(r.id).signature,[{text:r.name}]);});
test('password reset and deactivate revoke staff sessions',()=>{const {store,storage}=fixture();const staffSession=new CareStore(storage,storage);staffSession.login('staff','demo1234');store.resetPassword('u-staff','newdemopassword');staffSession.db=store.db;assert.equal(staffSession.user(),null);assert.throws(()=>store.login('staff','demo1234'));store.login('admin','demo1234');store.accountStatus('u-staff',false);assert.throws(()=>store.login('staff','newdemopassword'),/deactivated/);});
test('new facility duplicate and representative validation enforce source constraints',()=>{const {store}=fixture();assert.throws(()=>store.addFacility({name:'Oak Terrace Assisted Living'}),/already exists/);assert.throws(()=>store.saveResident({facilityId:'f1',name:'Demo',dob:'1940-01-01',signer:'POA',rep:{name:'Rep',email:'not-email',phone:'+14155550123'}}),/email/);assert.throws(()=>store.saveResident({facilityId:'f1',name:'Demo',dob:'1940-01-01',signer:'RP',rep:{name:'Rep',email:'rep@example.test',phone:'123'}}),/mobile/);});
test('missing Drive folder blocks uploads and save retries',()=>{const {store}=fixture(),r=store.saveResident({facilityId:'f4',name:'Missing Folder Demo',dob:'1940-01-01',signer:'Self'});store.sign(r.token,{accepted:true,signature:[{text:r.name}],signerName:r.name,relationship:'Self',failPdf:true});assert.throws(()=>store.retryPDF(r.id),/Drive folder/);assert.throws(()=>store.addDocument(r.id,{kind:'face',name:'demo.pdf'}),/Drive folder/);assert.equal(r.status,'Signed');});
test('create staff account then sign in only to its assigned facility',()=>{const {store}=fixture();store.account({username:'qa_staff',name:'QA Staff',facilityId:'f2',password:'fictionaldemo'});assert.throws(()=>store.account({username:'qa_staff',facilityId:'f1',password:'fictionaldemo'}),/taken/);store.login('qa_staff','fictionaldemo');assert.equal(store.visibleResidents().length,20);assert.equal(store.visibleFacilities()[0].id,'f2');});
test('profile settings cannot alter privileges; password change revokes the current session',()=>{const {store}=fixture();store.login('staff','demo1234');store.profile({name:'Demo Name',timezone:'Asia/Ho_Chi_Minh',theme:'dark',role:'Admin',facilityId:'f2'});assert.equal(store.user().role,'Staff');assert.equal(store.user().facilityId,'f1');assert.equal(store.user().name,'Demo Name');assert.throws(()=>store.password('wrong','nextdemopassword'),/current/);store.password('demo1234','nextdemopassword');assert.equal(store.user(),null);store.login('staff','nextdemopassword');assert.equal(store.user().timezone,'Asia/Ho_Chi_Minh');});
test('reset has a recovery flow for previous demo data and signatures',()=>{const {store}=fixture(),r=store.saveResident({facilityId:'f1',name:'Recoverable Demo',dob:'1940-01-01',signer:'Self'});store.sign(r.token,{accepted:true,signerName:r.name,relationship:'Self',signature:[{text:r.name}]});store.reset();assert.equal(store.user(),null);assert.equal(store.db.residents.length,62);assert(store.hasRecovery());store.restore();assert.equal(store.resident(r.id).status,'Signed');});
test('invalid calendar DOB and empty typed signatures fail without mutation',()=>{const {store}=fixture();assert.throws(()=>store.saveResident({facilityId:'f1',name:'Demo',dob:'1940-02-31',signer:'Self'}),/date of birth/);const r=store.db.residents.find(r=>r.status==='Pending');assert.throws(()=>store.sign(r.token,{accepted:true,signerName:r.name,relationship:'Self',signature:[{text:'   '}]}));assert.equal(r.status,'Pending');});
