/* Shared screens and interactions: UI V1 / UI V2 use the same consent domain. */
'use strict';
const careStore=new CareDomain.CareStore(localStorage,localStorage);
const legacyCarePages={facilities:facilitiesPage,facility:facilityPage,users:usersPage,activity:activityPage};
let careState={facility:'all',status:'all',group:'all',channel:'all',purpose:'all',delivery:'all',from:'',to:'',settings:'profile',authError:'',loginError:'',signatureMode:'draw',strokes:[],typedSignature:'',sort:'name',showGuide:false};
const careParams=()=>new URLSearchParams(location.hash.split('?')[1]||'');
const careB=(label,action,id='',type='',sym='',extra='')=>`<button type="button" class="btn ${type}" data-care="${action}" data-id="${esc(id)}" ${extra}>${sym?icon(sym):''}${esc(label)}</button>`;
const careLink=(label,route,type='')=>`<a class="btn ${type}" href="#${route}">${esc(label)}</a>`;
const careField=(label,name,value='',type='text',extra='')=>field(label,name,value,type,extra);
function careSelect(label,name,options,value='',extra=''){return `<label class="field"><span>${esc(label)}</span><select name="${name}" ${extra}>${options.map(([v,t])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;}
const careTime=(at)=>at?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:careStore.user()?.timezone||'America/Los_Angeles'}).format(new Date(at)):'—';
function careCard(title,html,extra=''){return `<section class="care-card ${extra}"><h2>${esc(title)}</h2>${html}</section>`;}
function careError(message){return `<div class="care-error" role="alert">${esc(message)}</div>`;}
function careNavigate(route){screen.query='';screen.page=1;screen.tab='all';careState.group='all';careState.status='all';if(location.hash==='#'+route)render();else location.hash=route;}
function carePublic(html){$('#app').innerHTML=`<div class="care-public"><header class="care-public-head"><a class="care-wordmark" href="#${careStore.user()?isV2()?'v2':'facilities':'login'}">ENT Care</a><div class="header-buttons">${themeSwitch()}${editionButtons()}${careB('Demo guide','guide')}</div></header><main id="main" tabindex="-1">${html}</main><footer>ENT Senior Care Group · Fictional demo · All changes stay in this browser.</footer></div>`;enhanceSelects($('#app'));syncThemeAssets();careInitCanvas();}
function carePrepareRoute(){
 const path=location.hash.slice(1).split('?')[0].replace(/^\//,'');
 const scenario=careParams().get('case');
 if(scenario&&['facility-collecting','facility-ready','facility-scheduled','facility-empty','resident-create','clinic-schedule'].includes(scenario)){screen.careFacility=scenario==='facility-ready'||scenario==='clinic-schedule'?'f2':scenario==='facility-scheduled'?'f3':scenario==='facility-empty'?'f4':'f1';screen.caseModal=null;if(scenario==='resident-create')screen.route='resident-new';if(scenario==='clinic-schedule'&&careState.caseKey!==scenario){careState.caseSchedule=true;careState.caseKey=scenario;}}
 if(scenario==='facility-create'){screen.route='facility-new';screen.caseModal=null;}
 if(!scenario)careState.caseKey=null;
 if(scenario==='users-inactive')screen.tab='Deactivated';
 if(path.startsWith('sign/')){screen.route='sign';screen.careToken=path.slice(5);}else if(path==='sign'){screen.careToken=careParams().get('token');}
 const aliases={accounts:'users','facilities/new':'facility-new','residents/new':'resident-new'};
 if(aliases[path])screen.route=aliases[path];
 if(/^facilities\/[^/]+$/.test(path)&&path!=='facilities/new'){screen.route='facility';screen.careFacility=path.split('/')[1];}
 if(/^residents\/[^/]+(?:\/edit)?$/.test(path)&&path!=='residents/new'){screen.route=path.endsWith('/edit')?'resident-edit':'resident';screen.careResident=path.split('/')[1];}
 if(screen.route==='sign'){careStore.rollCycles();carePublic(careSigningPage());return false;}
 if(screen.route==='login'){carePublic(careState.authError?careAuthErrorPage():careLoginPage());return false;}
 careSyncOperations();
 const u=careStore.user();if(!u){carePublic(careLoginPage());return false;}
 if(u.role!=='Admin'&&['users','facility-new','census','intake','cases'].includes(screen.route)){carePublic(careAccessPage());return false;}
 if(careStore.storageError)console.warn('Browser storage unavailable.');
 return true;
}
function careLoginPage(){return `<div class="care-login"><section class="care-login-form"><span class="eyebrow">Care team portal</span><h1>Sign in</h1><p>Use the account your ENT administrator gave you.</p><form id="care-login">${careField('Username','username','','text','required autocomplete="username"')}${careField('Password','password','','password','required autocomplete="current-password"')}<label class="checkline"><input type="checkbox" data-care-show-password>Show password</label><div id="care-form-error" aria-live="polite">${careState.loginError?careError(careState.loginError):''}</div><button class="btn primary large" type="submit">Sign in</button></form><p class="care-small">Need access? Contact your administrator.</p><div class="care-demo-accounts"><h3>Try a demo account</h3><p>Password: <code>demo1234</code></p>${careB('ENT admin','login-demo','admin')}${careB('Facility staff','login-demo','staff')}<div>${careB('Deactivated account','login-demo','locked','ghost')}${careB('Non-ENT account','login-demo','platform','ghost')}</div></div></section><section class="care-login-art">${isV2()?v2ClinicArtwork():companyIcon(0)}<h2>Every resident. Every clinic day.</h2><p>Collect consent, resolve requests and keep your care team ready for the next visit.</p><div class="care-login-features"><span>Resident roster</span><span>Consent & documents</span><span>Clinic scheduling</span></div></section></div>`;}
function careAccessPage(){return `<div class="care-message"><h1>Access restricted</h1><p>This page is available to ENT admins. Your staff account can manage residents at your assigned facility.</p>${careLink('Open my residents','residents','primary')}${careB('Switch account','guide')}</div>`;}
function careCurrentFacility(){return careParams().get('fid')||careParams().get('facilityId')||(careParams().has('case')?screen.careFacility:null)||careStore.user()?.facilityId||'f1';}
function careCurrentResident(){return careParams().get('id')||screen.careResident;}
function careProfileMarkup(){const u=careStore.user();return `<button class="profile" data-care="profile"><span class="avatar-initials">${esc((u?.name||u?.username||'ENT').split(' ').map(n=>n[0]).slice(0,2).join(''))}</span><span class="profile-name"><strong>${esc(u?.name||u?.username)}</strong><small>${esc(u?.role)}${u?.facilityId?' · '+esc(careStore.db.facilities.find(f=>f.id===u.facilityId)?.name||''):''}</small></span>${icon('dropdown')}</button>`;}
function careNavigation(nav){const u=careStore.user();return (u?.role==='Admin'?nav('facilities','Facilities','building'): '')+nav('residents','Residents','users')+(u?.role==='Admin'?nav('census','Census audit','census')+nav('intake','Face sheet intake','file')+nav('users','Staff accounts','users'):'')+nav('activity','Activity log','activity')+nav('settings','Settings','kit');}
function careV2Links(){const staff=careStore.user()?.role==='Staff';return v2Links.filter(x=>!staff||!['facilities','census','intake','users','cases'].includes(x[0])).map(x=>x[0]==='users'?['users','Staff accounts','users']:x[0]==='kit?view=settings'?['settings','Settings','profile']:x).flatMap(x=>x[0]==='v2'?[x,['residents','Residents','users']]:[x]);}
function careFavoriteMarkup(){return careStore.visibleFacilities().slice(0,3).map((f,i)=>`<a class="favorite" href="#facility?fid=${f.id}"><span class="folder-icon folder-${i}">${icon('folder')}</span><span>${esc(f.name)}</span></a>`).join('');}
function careAfterRender(){if(careState.caseSchedule){careState.caseSchedule=false;requestAnimationFrame(()=>document.querySelector('[data-care="schedule"]')?.click());}const bottom=$('.sidebar-bottom');if(bottom&&!bottom.querySelector('.navitem[data-care="guide"]'))bottom.insertAdjacentHTML('afterbegin',`<button class="navitem" data-care="guide">${icon('info')}<span>Demo guide · switch role</span></button>`);if(screen.route==='kit'&&kitView()==='settings'){const heading=$('.kit-page-head,.pagehead');heading?.insertAdjacentHTML('afterend',`<div class="care-kit-account">${careLink('Profile, password & sessions','settings')}</div>`);}if(careStore.storageError&&!$('#care-storage-warning'))$('#main').insertAdjacentHTML('afterbegin',`<div id="care-storage-warning">${note('Browser storage is full or unavailable. New changes may not survive reload.')}</div>`);}
function careFacilitiesPage(){const ff=careStore.visibleFacilities(),filtered=ff.filter(f=>(f.name+' '+f.address).toLowerCase().includes(screen.query.toLowerCase())&&(screen.tab==='all'||screen.tab==='ready'&&careStore.summary(f).status==='Ready to schedule'||screen.tab==='scheduled'&&careStore.summary(f).exam));return pageHead('Facilities','Track consents, scheduling alerts and upcoming clinic days.',careStore.user().role==='Admin'?careLink('New facility','facility-new','primary'):'')+metrics([['Facilities',ff.length,'In your care network'],['Residents',careStore.visibleResidents().length,'Across these facilities'],['Ready to schedule',ff.filter(f=>careStore.summary(f).status==='Ready to schedule').length,'Threshold reached']])+`<div class="sectionhead"><h2>Facility directory</h2><div class="filters">${search('Search facilities…')}${selectFilter('Facility status','tab',[['all','All facilities'],['ready','Ready to schedule'],['scheduled','Scheduled']])}</div></div>`+table(['Facility','Residents','Signed / threshold','Status','Next exam',''],filtered.map((f,i)=>{const s=careStore.summary(f);return `<tr><td><div class="identity-cell">${companyIcon(i)}<div><a class="cell-link" href="#facility?fid=${f.id}">${esc(f.name)}</a><small>${esc(f.address)}</small></div></div></td><td>${s.count}</td><td>${progress({...f,signed:s.ready})}<small>${s.signed} signed · ${s.unsigned} not signed</small></td><td>${badge(s.status,s.exam?'clear':s.status==='Ready to schedule'?'dark':'')}<small>${f.alertAt?'Alert delivered to PCC':''}</small></td><td>${date(s.exam)}</td><td>${careLink('Open','facility?fid='+f.id,'small')}</td></tr>`;}).join(''),850)+tableFoot(filtered.length,'facilities');}
function careFacilityPage(){let f;try{f=careStore.facility(careCurrentFacility());}catch(e){return careMissing(e.message);}const s=careStore.summary(f),admin=careStore.user().role==='Admin';const rows=careStore.visibleResidents(f.id).filter(r=>(r.name+' '+r.room).toLowerCase().includes(screen.query.toLowerCase()));return `<div class="care-breadcrumb">${careLink('Facilities','facilities','ghost')}<span>/ ${esc(f.name)}</span></div>`+pageHead(esc(f.name),esc(f.address),careLink('Add resident','resident-new?fid='+f.id,'primary'))+`<div class="care-content"><div class="care-grid three">${careCard(s.exam?'Signed awaiting scheduling':'Signed for the next clinic',`<strong class="care-number">${s.ready}<span> / ${f.threshold}</span></strong>${progress({...f,signed:s.ready})}<p>${s.exam?s.signed-s.ready+' booked · '+s.ready+' not scheduled':s.signed+' signed in this round'} · ${s.unsigned} awaiting consent</p>${admin?careB('Change threshold','threshold',f.id,'small','',s.exam?'disabled':''):''}`)}${careCard('Clinic scheduling',`<strong>${s.exam?date(s.exam):'Not scheduled'}</strong><p>${f.alertAt?'Alert delivered to pcc@entscg.com · '+careTime(f.alertAt):s.exam?'New signatures join this clinic day automatically.':'Alert sends when the consent threshold is reached.'}</p>${admin?careB(s.exam?'Change exam date':'Mark scheduled','schedule',f.id,'small','clock',!s.exam&&!s.ready?'disabled':''):''}`)}${careCard('Facility information',`<dl class="care-info"><dt>ID</dt><dd>${esc(f.id)}</dd><dt>Contact</dt><dd>${esc(f.contact)}<small>${esc(f.email)}<br>${esc(f.phone)}</small></dd><dt>Timezone</dt><dd>${esc(f.timezone)}</dd><dt>Drive folder</dt><dd>${f.drive?careB('View demo folder','folder',f.id,'small','folder'):'Not configured'}</dd></dl>` )}</div></div><div class="sectionhead"><h2>Residents</h2><div class="filters">${search('Search residents or room…')}${careStore.user().role==='Admin'?careB('Audit census','audit',f.id,'','census')+careB('Face sheet intake','intake',f.id,'','file'):''}${careLink('Full roster','residents?fid='+f.id)}</div></div>`+table(['Resident','Room','Signer','Consent','Signed copy','Exam date'],rows.map(r=>`<tr><td><a class="cell-link" href="#resident?id=${r.id}">${esc(r.name)}</a><small>${date(r.dob)}</small></td><td>${esc(r.room)||'—'}</td><td>${esc(r.signer==='Self'?'Resident':r.signer)}<small>${esc(r.rep?.name||'')}</small></td><td>${careStatus(r)}</td><td>${r.status==='Signed'?careB(r.pdf?'View PDF':'Retry saving PDF',r.pdf?'pdf':'retry-pdf',r.id,'small'):'—'}</td><td>${date(r.visitDate)}</td></tr>`).join(''),800)+tableFoot(rows.length,'residents');}
function careMissing(message){return `<div class="care-message"><h1>Page unavailable</h1><p>${esc(message)}</p>${careLink('Back to residents','residents','primary')}</div>`;}
function careStatus(r){return badge(r.status,r.status==='Signed'?'clear':r.status==='Do not contact'?'':'pending');}
function careGroup(r){if(r.status==='Do not contact')return 'done';if(r.deliveries.some(d=>d.status==='Failed')||r.status==='Signed'&&!r.pdf||['Pending','No response'].includes(r.status))return 'needs';return r.status==='Signed'?'done':'waiting';}
function careNext(r){if(r.status==='Do not contact')return '<span class="care-small">Family declined</span>';const failed=r.deliveries.find(d=>d.status==='Failed');if(failed)return careB('Edit '+(failed.channel==='EMAIL'?'email':'phone'),'edit-resident',r.id,'small')+' '+careB('Retry '+failed.channel,'send',r.id,'small','',`data-channel="${failed.channel}"`);if(r.status==='Signed')return careB(r.pdf?'View PDF':'Retry saving PDF',r.pdf?'pdf':'retry-pdf',r.id,'small');if(r.signer==='Self')return careLink('Sign now','sign?token='+r.token,'small');return careB(['Sent','Reminded','No response'].includes(r.status)?'Resend link':'Send link','send',r.id,'small');}
function careResidentsPage(){const u=careStore.user(),fid=careParams().get('fid')||careState.facility;const rr=careStore.visibleResidents(fid==='all'?null:fid),groups={all:rr.length,needs:rr.filter(r=>careGroup(r)==='needs').length,waiting:rr.filter(r=>careGroup(r)==='waiting').length,done:rr.filter(r=>careGroup(r)==='done').length};const filtered=rr.filter(r=>(r.name+' '+r.room+' '+(r.rep?.name||'')).toLowerCase().includes(screen.query.toLowerCase())&&(careState.group==='all'||careGroup(r)===careState.group)&&(careState.status==='all'||r.status===careState.status)).sort((a,b)=>careState.sort==='name'?a.name.localeCompare(b.name):careState.sort==='room'?a.room.localeCompare(b.room,undefined,{numeric:true}):careGroup(a).localeCompare(careGroup(b)));return pageHead('Residents','Manage signing requests and resident documents.',careLink('Add resident','resident-new'+(fid!=='all'?'?fid='+fid:''),'primary'))+`<div class="care-roster-toolbar">${tabs([['all','All residents',groups.all],['needs','Needs attention',groups.needs],['waiting','Waiting',groups.waiting],['done','Done',groups.done]],careState.group,'care-group')}<div class="filters">${search('Search residents or room…')}${u.role==='Admin'?careSelect('Facility','facility-filter',[['all','All facilities'],...careStore.visibleFacilities().map(f=>[f.id,f.name])],fid,'data-care-filter="facility"'):''}${careSelect('Consent status','status-filter',[['all','All statuses'],...['Pending','Sent','Reminded','No response','Signed','Do not contact'].map(s=>[s,s])],careState.status,'data-care-filter="status"')}${careSelect('Sort','sort',[['name','Name A–Z'],['room','Room'],['action','Next action']],careState.sort,'data-care-filter="sort"')}</div></div>`+table(['Resident','Facility','Room','Signing as','Consent','Next action',''],filtered.map(r=>`<tr><td><a class="cell-link" href="#resident?id=${r.id}">${esc(r.name)}</a><small>${date(r.dob)}</small></td><td>${esc(careStore.db.facilities.find(f=>f.id===r.facilityId)?.name)}</td><td>${esc(r.room)||'—'}</td><td>${esc(r.signer==='Self'?'Resident':r.signer)}<small>${esc(r.rep?.name||'')}</small></td><td>${careStatus(r)}<small>${careGroup(r)==='needs'?'Needs attention':r.status==='Signed'?'Signed '+date(r.signedAt.slice(0,10)):'Awaiting signature'}</small></td><td><div class="inline-actions">${careNext(r)}</div></td><td>${careLink('Open','resident?id='+r.id,'small')}</td></tr>`).join(''),1000)+tableFoot(filtered.length,'residents');}
function careResidentPage(){let r;try{r=careStore.resident(careCurrentResident());}catch(e){return careMissing(e.message);}const f=careStore.facility(r.facilityId);let issues=r.deliveries.filter(d=>d.status==='Failed').map(d=>careCard(d.channel==='EMAIL'?'Email not sent':'SMS failed',`<p>Could not deliver to ${esc(d.recipient)}. Update the contact details or retry this channel.</p><div class="inline-actions">${careB('Edit contact','edit-resident',r.id)}${careB('Retry '+d.channel,'send',r.id,'','','data-channel="'+d.channel+'"')}</div>`,'care-issue')).join('');if(r.status==='Signed'&&!r.pdf)issues+=careCard('Signed copy was not saved',`<p>The signature is recorded. Retry saving its PDF without asking the resident to sign again.</p>${careB('Retry saving PDF','retry-pdf',r.id)}`,'care-issue');return `<div class="care-breadcrumb">${careLink(f.name,'facility?fid='+f.id,'ghost')}<span>/ Resident</span></div>`+pageHead(esc(r.name),`${date(r.dob)} · Room ${esc(r.room)||'—'}`,careB('Edit resident','edit-resident',r.id)) +`<div class="care-content">${issues}<div class="care-grid three">${careCard('Signing as',`<strong>${r.signer==='Self'?'The resident':r.signer==='POA'?'Power of Attorney':'Responsible Party'}</strong>${r.rep?`<p>${esc(r.rep.name)}<br>${esc(r.rep.email)}<br>${esc(r.rep.phone)}</p>`:'<p>Signs in person on this device.</p>'}<p>Resident ID: <code>${esc(r.id)}</code></p>`)}${careCard('Documents',careDocuments(r))}${careCard('Consent',`${careStatus(r)}<p>${r.signedAt?'Signed '+careTime(r.signedAt)+' by '+esc(r.signerName):'Consent for the current clinic round.'}</p><div class="care-action-stack">${careNext(r)}${r.status!=='Signed'?`${careB('Copy signing link','copy-link',r.id)}${r.status!=='Do not contact'?careLink('Open signing page','sign?token='+r.token):''}${careB('Replace link','replace-link',r.id)}${careB(r.status==='Do not contact'?'Allow contact':'Do not contact','dnc',r.id)}`:''}${['Sent','Reminded','No response'].includes(r.status)?careB('Send reminder','remind',r.id):''}</div>` )}</div>${r.visitDate?note('Next clinic day: '+date(r.visitDate)):''}${r.deliveries.length?careCard('Delivery results',`<div class="care-deliveries">${r.deliveries.map(d=>`<div><strong>${esc(d.channel)}</strong>${badge(d.status,d.status==='Delivered'?'clear':'pending')}<p>${esc(d.recipient)}</p><small>${careTime(d.at)}</small></div>`).join('')}</div>`):''}${careCard('History',`<ol class="care-timeline">${[...r.history].sort((a,b)=>b.at.localeCompare(a.at)).map(h=>`<li><div><strong>${esc(h.title)}</strong><p>${esc(h.detail||'')}</p></div><time>${careTime(h.at)}</time></li>`).join('')}</ol>`)}${r.archives?.length?careCard('Previous clinic rounds',r.archives.map((a,i)=>`<div class="care-archive"><span>${date(a.visitDate)} · signed ${careTime(a.signedAt)}</span>${careB('View archived consent','archive-pdf',r.id,'small','',`data-index="${i}"`)}</div>`).join('')):''}</div>`;}
function careDocuments(r){return ['face','insurance'].map(kind=>{const doc=r.documents.find(d=>d.kind===kind);return `<div class="care-document"><strong>${kind==='face'?'Face sheet':'Insurance card'}</strong><p>${doc?careB(doc.name,'document',r.id,'ghost small','file',`data-kind="${kind}"`):'Not uploaded'}</p><label class="btn small">${doc?'Replace':'Upload'}<input type="file" data-care-upload="${kind}" data-id="${r.id}" accept="application/pdf,image/png,image/jpeg" class="visually-hidden"></label></div>`;}).join('');}
function careResidentForm(){let r=null;if(screen.route==='resident-edit'){try{r=careStore.resident(careCurrentResident());}catch(e){return careMissing(e.message);}}const fid=r?.facilityId||careParams().get('fid')||(careParams().get('case')==='resident-create'?'f1':null)||careStore.user().facilityId||careStore.visibleFacilities()[0]?.id;const signer=r?.signer||'';return pageHead(r?'Edit resident':'Add resident','Enter resident details and identify who will sign.')+`<div class="care-content care-form-width"><form id="care-resident-form" data-id="${r?.id||''}">${careCard('1. Resident',`<div class="formgrid">${careSelect('Facility *','facilityId',careStore.visibleFacilities().map(f=>[f.id,f.name]),fid,r?'disabled':'required')}${r?`<input type="hidden" name="facilityId" value="${r.facilityId}">`:''}${careField('Full name *','name',r?.name||'','text','required maxlength="120"')}${careField('Date of birth *','dob',r?.dob||'','date',`required max="${careStore.today()}"`)}${careField('Room / apartment','room',r?.room||'','text','maxlength="40"')}</div>`)}${careCard('2. Who will sign?',`<fieldset class="care-radio-options"><legend class="visually-hidden">Who will sign?</legend>${[['Self','The resident','Signs in person on this device'],['POA','Power of Attorney (POA)','Signs through a link you send'],['RP','Responsible Party (RP)','Signs through a link you send']].map(([v,t,desc])=>`<label><input type="radio" name="signer" value="${v}" ${signer===v?'checked':''} required><span><strong>${t}</strong><small>${desc}</small></span></label>`).join('')}</fieldset>`)}<section id="care-representative" class="care-card" ${!signer||signer==='Self'?'hidden':''}><h2>3. Representative details</h2><p>All three fields are required for POA and RP.</p><div class="formgrid">${careField('Representative full name *','repName',r?.rep?.name||'','text',!signer||signer==='Self'?'disabled':'required')}${careField('Mobile phone *','repPhone',r?.rep?.phone||'+1','tel',`${!signer||signer==='Self'?'disabled':'required'} placeholder="+14155550123" pattern="[+][1-9][0-9]{7,14}"`)}${careField('Email *','repEmail',r?.rep?.email||'','email',!signer||signer==='Self'?'disabled':'required')}</div><p class="care-small">Include the country code. For example: US +1, UK +44, Vietnam +84.</p></section><div id="care-form-error" aria-live="polite"></div><div class="formfooter">${careLink('Cancel',r?'resident?id='+r.id:'residents','ghost')}<button class="btn" type="submit" name="intent" value="later">${r?'Save changes':'Save, send later'}</button>${!r?'<button class="btn primary" type="submit" name="intent" value="send">Save & continue</button>':''}</div></form></div>`;}
function careFacilityForm(){return pageHead('New facility','Create a facility and its primary care-team contact.')+`<div class="care-content care-form-width"><form id="care-facility-form">${careCard('Facility details',`<div class="formgrid">${careField('Facility name *','name','','text','required maxlength="120"')}${careField('Address *','address','','text','required')}${careField('Contact name *','contact','','text','required')}${careField('Contact email *','email','','email','required')}${careField('Contact phone *','phone','+1','tel','required pattern="[+][1-9][0-9]{7,14}"')}${careSelect('Timezone *','timezone',careTimezones(),'America/Los_Angeles','required')}</div><p>New facilities start with a threshold of 15 signed consents. Configure their Drive folder before uploading documents.</p>`)}<div id="care-form-error" aria-live="polite"></div><div class="formfooter">${careLink('Cancel','facilities','ghost')}<button class="btn primary" type="submit">Create facility</button></div></form></div>`;}
function careTimezones(){return [...new Set(['America/Los_Angeles','America/Denver','America/Chicago','America/New_York','Pacific/Honolulu','Europe/London','Asia/Ho_Chi_Minh','UTC',...(Intl.supportedValuesOf?.('timeZone')||[])])].map(z=>[z,z.replaceAll('_',' ')]);}
function careUsersPage(){const uu=careStore.db.users.filter(u=>u.type==='ENT'&&u.role==='Staff').filter(u=>(u.name+' '+u.username).toLowerCase().includes(screen.query.toLowerCase())&&(screen.tab==='all'||u.status===screen.tab));return pageHead('Staff accounts','Give facility staff access and manage their accounts.',careB('New staff account','account-new','','primary','plus'))+`<div class="care-roster-toolbar">${tabs([['all','All accounts'],['Active','Active'],['Deactivated','Deactivated']],screen.tab)}${search('Search staff accounts…')}</div>`+table(['Staff member','Username','Facility','Status','Actions'],uu.map(u=>`<tr><td><div class="identity-cell"><span class="avatar-initials">${esc((u.name||u.username).slice(0,2).toUpperCase())}</span><strong>${esc(u.name||u.username)}</strong></div></td><td><code>${esc(u.username)}</code></td><td>${esc(careStore.db.facilities.find(f=>f.id===u.facilityId)?.name||'—')}</td><td>${badge(u.status,u.status==='Active'?'clear':'')}</td><td><div class="inline-actions">${careB('Edit','account-edit',u.id,'small')}${careB('Reset password','account-password',u.id,'small')}${careB(u.status==='Active'?'Deactivate':'Activate','account-status',u.id,'small')}</div></td></tr>`).join(''),850)+tableFoot(uu.length,'staff accounts');}
function careAccountDialog(uid){const u=uid?careStore.db.users.find(u=>u.id===uid):null;modal(`<h2>${u?'Edit staff account':'New staff account'}</h2><form id="care-account-form" data-id="${u?.id||''}"><div class="formgrid">${careField('Username *','username',u?.username||'','text','required pattern="[a-z0-9._-]{3,}" autocomplete="off"')}${careField('Display name','name',u?.name||'')}${careSelect('Facility *','facilityId',careStore.db.facilities.map(f=>[f.id,f.name]),u?.facilityId||careParams().get('fid')||'f1','required')}${!u?careField('Temporary password *','password','demo1234','password','required minlength="8" autocomplete="new-password"'):''}</div><p>${u?'Changing this account revokes its current sessions.':'Share these demo credentials with the staff member. Passwords require at least 8 characters.'}</p><div id="care-form-error" aria-live="polite"></div><div class="formfooter">${careB('Cancel','modal-close')}<button class="btn primary">${u?'Save changes':'Create account'}</button></div></form>`);}
function careActivityPage(){const u=careStore.user(),allowed=careStore.visibleFacilities().map(f=>f.id);let mm=careStore.db.messages.filter(m=>u.role==='Admin'||allowed.includes(m.facilityId));mm=mm.filter(m=>([m.recipient,careStore.db.residents.find(r=>r.id===m.residentId)?.name,careStore.db.facilities.find(f=>f.id===m.facilityId)?.name].join(' ')).toLowerCase().includes(screen.query.toLowerCase())&&(careState.channel==='all'||m.channel===careState.channel)&&(careState.purpose==='all'||m.purpose===careState.purpose)&&(careState.delivery==='all'||m.status===careState.delivery)&&(careState.facility==='all'||m.facilityId===careState.facility)&&(!careState.from||m.at.slice(0,10)>=careState.from)&&(!careState.to||m.at.slice(0,10)<=careState.to)).sort((a,b)=>b.at.localeCompare(a.at));const filters=(label,key,opts)=>careSelect(label,key,[['all','All '+label.toLowerCase()],...opts.map(v=>[v,v])],careState[key],`data-care-filter="${key}"`);return pageHead('Activity log','Delivery attempts and scheduling alerts for your care team.',careB('Export CSV','activity-export'))+`<div class="care-roster-toolbar"><div class="filters">${search('Search activity…')}${filters('Channels','channel',['EMAIL','SMS','VOICE'])}${filters('Purposes','purpose',['Request','Reminder','Alert'])}${filters('Results','delivery',['Delivered','Failed'])}${u.role==='Admin'?careSelect('Facility','facility',[['all','All facilities'],...careStore.visibleFacilities().map(f=>[f.id,f.name])],careState.facility,'data-care-filter="facility"'):''}</div><div class="inline-actions care-date-filters">${careField('From','from',careState.from,'date','data-care-filter="from"')}${careField('To','to',careState.to,'date','data-care-filter="to"')}${careB('Reset filters','activity-clear')}</div></div>`+table(['Time','Resident / facility','Channel','Purpose','Recipient','Result'],mm.map(m=>`<tr><td>${careTime(m.at)}</td><td>${m.residentId?`<a class="cell-link" href="#resident?id=${m.residentId}">${esc(careStore.db.residents.find(r=>r.id===m.residentId)?.name)}</a>`:'Scheduling team'}<small>${esc(careStore.db.facilities.find(f=>f.id===m.facilityId)?.name)}</small></td><td>${esc(m.channel)}</td><td>${esc(m.purpose)}</td><td>${esc(m.recipient)}</td><td>${badge(m.status,m.status==='Delivered'?'clear':'pending')}<small>${esc(m.error||'')}</small></td></tr>`).join(''),950)+tableFoot(mm.length,'messages')+`<div class="care-content">${careCard('Workspace history',`<ol class="care-timeline">${careStore.db.events.filter(e=>u.role==='Admin'||e.facilityId===u.facilityId).slice(0,30).map(e=>`<li><div><strong>${esc(e.title)}</strong><p>${esc(e.detail)}</p></div><time>${careTime(e.at)}</time></li>`).join('')||'<li>No recent changes.</li>'}</ol>`)}</div>`;}
function careSettingsPage(){const u=careStore.user(),tab=careParams().get('tab')||careState.settings;let html='';if(tab==='profile')html=`<form id="care-profile-form">${careField('Username','username',u.username,'text','disabled')}${careField('Display name','name',u.name||'')}${careField('Email','email',u.email||'','email')}<div id="care-form-error"></div><div class="formfooter"><button class="btn primary">Save profile</button></div></form>`;else if(tab==='preferences')html=`<form id="care-preferences-form">${careSelect('Timezone','timezone',careTimezones(),u.timezone)}${careSelect('Theme','theme',[['light','Light'],['dark','Dark'],['system','System']],u.theme||colorTheme)}<p>Dates use your timezone. Clinic days use the facility’s timezone.</p><div id="care-form-error"></div><div class="formfooter"><button class="btn primary">Save preferences</button></div></form>`;else if(tab==='password')html=`<form id="care-password-form">${careField('Current password *','current','','password','required autocomplete="current-password"')}${careField('New password *','next','','password','required minlength="8" autocomplete="new-password"')}${careField('Confirm new password *','confirm','','password','required minlength="8" autocomplete="new-password"')}<p>At least 8 characters. Changing your password signs you out of every demo session.</p><div id="care-form-error"></div><div class="formfooter"><button class="btn primary">Update password</button></div></form>`;else html=`<p>You are signed in as <strong>${esc(u.username)}</strong> on this browser.</p><div class="care-session"><div>${icon('users')}<strong>Current browser</strong><small>${esc(u.role)} · Active now</small></div>${badge('Current session','clear')}</div><p>Sign out everywhere revokes this account’s other demo browser sessions.</p><div class="formfooter">${careB('Sign out everywhere','logout-all','','primary')}</div>`;return pageHead('Settings','Your profile, preferences, password and sessions.')+`<div class="care-settings-tabs">${tabs([['profile','Profile'],['preferences','Preferences'],['password','Password'],['sessions','Sessions']],tab,'care-settings-tab')}</div><div class="care-content care-form-width">${careCard(tab[0].toUpperCase()+tab.slice(1),html)}${careCard('Workspace tools',`<p>Open the existing UI library’s workspace settings, integrations and preferences.</p>${careLink('Workspace settings','kit?view=settings')}`)}</div>`;}
function careSigningPage(){const token=screen.careToken,r=careStore.signing(token);if(!r)return `<div class="care-message"><h1>This link is not valid</h1><p>It may have been replaced. Ask the facility for a new signing link.</p>${careB('Open demo guide','guide')}</div>`;const f=careStore.db.facilities.find(f=>f.id===r.facilityId);if(r.status==='Signed')return `<div class="care-message"><span class="care-success-icon">✓</span><h1>This consent has been signed</h1><p>${esc(r.name)} · ${esc(f.name)}</p><p>Signed ${careTime(r.signedAt)} by ${esc(r.signerName)}.</p>${r.pdf?careB('Download signed PDF','public-pdf',r.id,'primary'):note('The signature is recorded. The care team can retry saving the PDF.')}${careStore.user()?careLink('Back to resident','resident?id='+r.id):''}</div>`;if(r.status==='Do not contact')return `<div class="care-message"><h1>This request is paused</h1><p>Contact the facility if you wish to resume.</p>${careB('Demo guide','guide')}</div>`;return `<div class="care-signing"><div class="care-sign-head"><span class="eyebrow">ENT Senior Care Group</span><h1>Consent for ENT care</h1><p>${esc(r.name)} · ${esc(f.name)}</p>${note('Demo consent only. This signs a fictional record in this browser.')}</div><div class="care-grid signing"><section class="care-card care-consent-text"><h2>Consent</h2>${CareDomain.consentText.map(p=>`<p>${esc(p)}</p>`).join('')}</section><section class="care-card"><h2>Your signature</h2><form id="care-sign-form" data-token="${esc(token)}">${careField('Your full name *','signerName',r.rep?.name||r.name,'text','required')}${careSelect('Relationship *','relationship',[['Self','The resident'],['POA','Power of Attorney (POA)'],['RP','Responsible Party (RP)']],r.signer,'required')}<div class="care-signature-tabs"><button type="button" class="btn ${careState.signatureMode==='draw'?'selected':''}" data-care="signature-mode" data-mode="draw" aria-pressed="${careState.signatureMode==='draw'}">Draw signature</button><button type="button" class="btn ${careState.signatureMode==='type'?'selected':''}" data-care="signature-mode" data-mode="type" aria-pressed="${careState.signatureMode==='type'}">Type signature</button></div>${careState.signatureMode==='draw'?`<div class="care-signature-pad"><canvas id="care-signature-canvas" width="600" height="180" aria-label="Draw your signature. Use Type signature for keyboard entry."></canvas><span>Sign here</span></div>${careB('Clear signature','signature-clear','','ghost small')}`:careField('Type your signature *','typedSignature',careState.typedSignature,'text','required data-care-typed')}<label class="checkline care-certify"><input type="checkbox" name="accepted" required><span>I confirm that I am the resident or authorized to sign on their behalf, and I agree to the consent above.</span></label><div id="care-form-error" aria-live="polite"></div><button type="submit" class="btn primary large">Sign demo consent</button></form></section></div></div>`;}
function careInitCanvas(){const canvas=$('#care-signature-canvas');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.strokeStyle='#202124';ctx.lineWidth=2.4;ctx.lineCap='round';ctx.lineJoin='round';const paint=()=>{ctx.clearRect(0,0,600,180);for(const stroke of careState.strokes){ctx.beginPath();stroke.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();}};paint();let stroke=null;const point=e=>{const b=canvas.getBoundingClientRect();return [(e.clientX-b.left)*600/b.width,(e.clientY-b.top)*180/b.height];};canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);stroke=[point(e)];careState.strokes.push(stroke);});canvas.addEventListener('pointermove',e=>{if(!stroke)return;stroke.push(point(e));paint();});const stop=()=>{stroke=null;};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);}
function careGuide(){const user=careStore.user(),admin=user?.role==='Admin',staff=!!user,open=careStore.db.residents.find(r=>r.status!=='Signed'&&r.status!=='Do not contact'&&r.rep);const goto=(label,route,enabled=true)=>careB(label,'guide-go',route,'','',''+(!enabled?'disabled':''));modal(`<h2>Consentform demo</h2><p>All data is fictional and lives in this browser. Both editions share the same data.</p><div class="care-guide"><section><h3>Accounts · default password demo1234</h3>${careB('Sign in as ENT admin (admin)','login-demo','admin')}${careB('Sign in as facility staff (staff)','login-demo','staff')}${careB('Deactivated account (locked)','login-demo','locked')}${careB('Non-ENT account (platform)','login-demo','platform')}${careB('Sign out','logout')}<p>Current: ${esc(user?.name||'Signed out')} ${user?'· '+esc(user.role):''}</p></section><section><h3>Admin screens</h3>${goto('Facilities overview','facilities',admin)}${goto('Ready to schedule · Oak Terrace','facility?fid=f2',admin)}${goto('Booked clinic day · Bayview','facility?fid=f3',admin)}${goto('Add a facility','facility-new',admin)}${goto('Staff accounts','users',admin)}${!admin?'<p>Sign in as admin to open these screens.</p>':''}</section><section><h3>Staff & shared screens</h3>${goto('Residents roster','residents',staff)}${goto('Add a resident','resident-new',staff)}${goto('Activity log','activity',staff)}${goto('Settings','settings',staff)}</section><section><h3>Public signing pages</h3>${goto('Sign a consent · '+(open?.name||'No open requests'),'sign?token='+open?.token,!!open)}${goto('Link that was already signed','sign?token='+careStore.db.residents.find(r=>r.status==='Signed')?.token)}${goto('Invalid signing link','sign?token=not-a-real-token')}</section><section><h3>Failure paths & scheduling</h3><p>Representative emails containing <code>bounce</code> fail. Phones ending <code>0000</code> fail SMS. Signed PDFs can be retried separately. Palm Court has no Drive folder.</p><p>The initial seed has Sunrise Villa at 14/15 signatures. One more signature triggers its PCC scheduling alert.</p><p>After a booked clinic day passes, a new consent round starts.</p>${admin?careB('Preview next clinic round','advance-clock'):''}</section><section><h3>Data</h3>${careB('Reset all demo data','reset-confirm')}${careStore.hasRecovery()?careB('Restore previous demo data','restore-demo'):''}</section></div>`);$('#dialog').classList.add('care-guide-modal');}
function carePDF(r,title='Signed consent'){
 const safe=s=>String(s??'').normalize('NFKD').replace(/[’‘]/g,"'").replace(/[–—]/g,'-').replace(/[^\x20-\x7e]/g,'?').replace(/[\\()]/g,c=>'\\'+c);
 const lines=[title+' - ENT Senior Care Group','FICTIONAL DEMO - Browser-only record','Resident: '+r.name,'Facility: '+(careStore.db.facilities.find(f=>f.id===r.facilityId)?.name||''),'DOB: '+r.dob,'Resident ID: '+r.id,'',...CareDomain.consentText.flatMap(p=>{const words=p.split(' '),out=[];let line='';for(const w of words){if((line+' '+w).length>88){out.push(line);line=w;}else line+=(line?' ':'')+w;}return [...out,line,''];}),'Signed by: '+(r.signerName||r.name),'Relationship: '+(r.relationship||r.signer),'Signed at: '+(r.signedAt||''),'Clinic day: '+(r.visitDate||'Not scheduled')];
 let content='BT /F1 10 Tf 48 795 Td 14 TL '+lines.map((l,i)=>(i?'T* ':'')+'('+safe(l)+') Tj').join('\n')+' ET\n';
 if(r.signature?.[0]?.text)content+='BT /F2 24 Tf 48 240 Td ('+safe(r.signature[0].text)+') Tj ET\n';else if(Array.isArray(r.signature)){content+='0.13 0.14 0.15 RG 1.3 w\n';for(const stroke of r.signature){if(!Array.isArray(stroke))continue;content+=stroke.map(([x,y],i)=>`${(48+x*.75).toFixed(2)} ${(270-y*.75).toFixed(2)} ${i?'l':'m'}`).join('\n')+' S\n';}}else content+='BT /F2 24 Tf 48 240 Td ('+safe(r.signerName||r.name)+') Tj ET\n';
 const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 6 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${content.length} >>\nstream\n${content}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique >>'];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const x=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n \n').join('')+`trailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'});
}
function careDownload(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function careFileDB(action,key,blob){return new Promise((resolve,reject)=>{const request=indexedDB.open('ent-care-files',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('files',action==='get'?'readonly':'readwrite'),op=action==='get'?tx.objectStore('files').get(key):tx.objectStore('files').put(blob,key);op.onerror=()=>reject(op.error);op.onsuccess=()=>resolve(op.result);tx.oncomplete=()=>db.close();};});}
const carePages={facilities:careFacilitiesPage,facility:careFacilityPage,residents:careResidentsPage,resident:careResidentPage,'resident-new':careResidentForm,'resident-edit':careResidentForm,'facility-new':careFacilityForm,users:careUsersPage,activity:careActivityPage,settings:careSettingsPage};
function careFormError(form,error){const target=form.querySelector('#care-form-error')||$('#care-form-error');if(target)target.innerHTML=careError(error.message||error);else toast(error.message||error);}
let carePDFSnapshot=null;
function careShowPDF(r,title){carePDFSnapshot=r;modal(`<h2>${esc(title||'Signed consent PDF')}</h2><p>${esc(r.name)} · Fictional demo document</p>${carePDFPreview(r,title)}<div class="formfooter">${careB('Close','modal-close')}${careB('Download PDF','preview-download',r.id,'primary')}</div>`);$('#dialog').classList.add('care-pdf-modal');}
document.addEventListener('click',async e=>{
 const target=e.target.closest('[data-care]'),edition=e.target.closest('[data-action="open-kit"],[data-action="open-v2"]'),tab=e.target.closest('[data-action="care-group"],[data-action="care-settings-tab"]');
 if(edition&&(carePages[screen.route]||['login','sign'].includes(screen.route)||!careStore.user())){e.preventDefault();e.stopImmediatePropagation();if($('#dialog').open)closeModal();const draft=careCaptureForms();setDesignEdition(edition.dataset.action==='open-v2'?'v2':'figma');render();careRestoreForms(draft);return;}
 if(tab){e.preventDefault();e.stopImmediatePropagation();if(tab.dataset.action==='care-group'){careState.group=tab.dataset.value;screen.page=1;render();}else careNavigate('settings?tab='+tab.dataset.value);return;}
 if(!target)return;e.preventDefault();e.stopImmediatePropagation();const action=target.dataset.care,id=target.dataset.id;
 try{
  if(action==='login-again'){careState.authError='';careState.loginError='';render();return;}
  if(action==='guide'){careGuide();return;}
  if(action==='modal-close'){closeModal();return;}
  if(action==='guide-go'){closeModal();careNavigate(id);return;}
  if(action==='login-demo'){if($('#dialog').open)closeModal();try{careStore.logout();const u=careStore.login(id,careStore.db.users.find(u=>u.username===id)?.password||'demo1234');careState.loginError='';careState.authError='';careState.facility='all';careNavigate(u.role==='Admin'?isV2()?'v2':'facilities':'residents');}catch(err){careState.loginError=err.message;careState.authError=err.message.includes('deactivated')?'deactivated':err.message.includes('not an ENT')?'platform':'';careNavigate('login');render();}return;}
  if(action==='logout'||action==='logout-all'){careStore.logout(action==='logout-all');careState.loginError='';careState.authError='';if($('#dialog').open)closeModal();careNavigate('login');return;}
  if(action==='profile'){const u=careStore.auth();modal(`<h2>${esc(u.name||u.username)}</h2><p>${esc(u.role)} · ${esc(u.email||u.username)}</p><div class="care-action-stack">${careLink('Profile & settings','settings')}${careB('Switch demo role','guide')}${careB('Sign out','logout')}</div>`);return;}
  if(action==='audit'){careStore.admin();audit.facility=careStore.db.facilities.findIndex(f=>f.id===id)+1;careNavigate('census');return;}
  if(action==='intake'){careStore.admin();careState.intakeFacility=careStore.db.facilities.findIndex(f=>f.id===id)+1;intake.stage='upload';careNavigate('intake');return;}
  if(action==='edit-resident'){careStore.resident(id);careNavigate('resident-edit?id='+id);return;}
  if(action==='send'||action==='remind'){const dd=careStore.send(id,target.dataset.channel,action==='remind'?'Reminder':'Request');render();toast(dd.every(d=>d.status==='Failed')?'Request failed. Check contact details. Resident record is saved.':dd.some(d=>d.status==='Failed')?'Partially delivered. One channel needs attention.':'Demo '+(action==='remind'?'reminder':'request')+' delivered.');return;}
  if(action==='copy-link'||action==='copy-link-again'){const r=careStore.resident(id),url=location.href.split('#')[0]+'#sign?token='+r.token;try{await navigator.clipboard.writeText(url);toast('Signing link copied.');}catch{modal(`<h2>Signing link</h2><p>Copy this local demo link.</p>${careField('Signing link','link',url,'text','readonly')}<div class="formfooter">${careB('Close','modal-close')}${careLink('Open signing page','sign?token='+r.token,'primary')}</div>`);}return;}
  if(action==='replace-link'){const r=careStore.resident(id);modal(`<h2>Replace signing link?</h2><p>The previous link for ${esc(r.name)} will stop working, including a page already opened with that link.</p><div class="formfooter">${careB('Cancel','modal-close')}${careB('Replace link','replace-confirm',id,'primary')}</div>`);return;}
  if(action==='replace-confirm'){careStore.replaceLink(id);closeModal();render();toast('New link created. Previous link is invalid.');return;}
  if(action==='dnc'){const r=careStore.resident(id);modal(`<h2>${r.status==='Do not contact'?'Allow contact again?':'Mark do not contact?'}</h2><p>${r.status==='Do not contact'?'Signing requests may be sent again.':'Requests and reminders will stop for this family.'}</p><div class="formfooter">${careB('Cancel','modal-close')}${careB('Confirm','dnc-confirm',id,'primary')}</div>`);return;}
  if(action==='dnc-confirm'){const r=careStore.resident(id);careStore.doNotContact(id,r.status!=='Do not contact');closeModal();render();toast('Contact preference updated.');return;}
  if(action==='retry-pdf'){careStore.retryPDF(id);render();toast('Signed copy saved. Original signature preserved.');return;}
  if(action==='pdf'){const r=careStore.resident(id);if(!r.pdf)throw new Error('The signed PDF has not been saved.');careShowPDF(r);return;}
  if(action==='archive-pdf'){const r=careStore.resident(id),a=r.archives?.[Number(target.dataset.index)];if(!a)throw new Error('Archived consent unavailable.');careShowPDF({...r,...a},'Archived consent');return;}
  if(action==='preview-download'){if(!carePDFSnapshot)throw new Error('PDF preview unavailable.');careDownload(carePDF(carePDFSnapshot),'Consent_'+carePDFSnapshot.name.replaceAll(' ','_')+'.pdf');return;}
  if(action==='public-pdf'||action==='pdf-download'){const r=action==='public-pdf'?careStore.signing(screen.careToken):careStore.resident(id);if(!r||!r.pdf)throw new Error('Signed copy unavailable.');careDownload(carePDF(r),'Consent_'+r.name.replaceAll(' ','_')+'.pdf');return;}
  if(action==='document'){const r=careStore.resident(id),doc=r.documents.find(d=>d.kind===target.dataset.kind);if(!doc)throw new Error('Document not found.');const blob=doc.sample?carePDF({...r,signerName:'Sample document',signedAt:null},doc.kind==='face'?'Face sheet - demo sample':'Insurance card - demo sample'):await careFileDB('get',doc.key);if(!blob)throw new Error('This file is unavailable in browser storage. Upload it again.');careDownload(blob,doc.name);return;}
  if(action==='folder'){const f=careStore.facility(id);modal(`<h2>${esc(f.name)} · demo folder</h2><p>Folder ID: ${esc(f.id)}. Files below are stored locally for this prototype.</p><div class="care-folder-list">${careStore.visibleResidents(id).map(r=>`<a href="#resident?id=${r.id}"><strong>${esc(r.name)}</strong><small>${r.documents.length} documents · ${r.pdf?'Consent PDF saved':'No signed PDF'}</small></a>`).join('')||'<p>No resident documents yet.</p>'}</div>`);return;}
  if(action==='threshold'){const f=careStore.facility(id);if(careStore.summary(f).exam)throw new Error('Threshold is locked while a clinic day is scheduled.');modal(`<h2>Change scheduling threshold</h2><p>${esc(f.name)}</p><form id="care-threshold-form" data-id="${id}">${careField('Signed consents needed *','threshold',f.threshold,'number','required min="1" max="1000" step="1"')}<div id="care-form-error"></div><div class="formfooter">${careB('Cancel','modal-close')}<button class="btn primary">Save threshold</button></div></form>`);return;}
  if(action==='schedule'){const f=careStore.facility(id),s=careStore.summary(f);modal(`<h2>${s.exam?'Change exam date':'Mark scheduled'}</h2><p>${s.exam?'Update the date for residents booked on '+date(s.exam)+'.':s.ready+' signed residents will receive this exam date. Scheduling alerts clear when a clinic is booked.'}</p><form id="care-schedule-form" data-id="${id}" data-change="${!!s.exam}">${careField('Exam date *','day',s.exam||'','date',`required min="${careStore.today(f)}"`)}<p>Facility timezone: ${esc(f.timezone)}. Until this day passes, new signatures join this clinic day.</p><div id="care-form-error"></div><div class="formfooter">${careB('Cancel','modal-close')}<button class="btn primary">${s.exam?'Save date':'Mark scheduled'}</button></div></form>`);return;}
  if(action==='account-new'||action==='account-edit'){careStore.admin();careAccountDialog(action==='account-edit'?id:null);return;}
  if(action==='account-password'){careStore.admin();const u=careStore.db.users.find(u=>u.id===id);modal(`<h2>Reset staff password</h2><p>${esc(u.username)} · All sessions for this account will be revoked.</p><form id="care-account-password" data-id="${id}">${careField('New password *','password','','password','required minlength="8" autocomplete="new-password"')}<div id="care-form-error"></div><div class="formfooter">${careB('Cancel','modal-close')}<button class="btn primary">Reset password</button></div></form>`);return;}
  if(action==='account-status'){careStore.admin();const u=careStore.db.users.find(u=>u.id===id);modal(`<h2>${u.status==='Active'?'Deactivate':'Activate'} ${esc(u.username)}?</h2><p>${u.status==='Active'?'They will be signed out and unable to access the care portal.':'They will be able to sign in to their assigned facility.'}</p><div class="formfooter">${careB('Cancel','modal-close')}${careB('Confirm','account-status-confirm',id,'primary')}</div>`);return;}
  if(action==='account-status-confirm'){const u=careStore.db.users.find(u=>u.id===id);careStore.accountStatus(id,u.status!=='Active');closeModal();render();toast('Staff account updated.');return;}
  if(action==='signature-mode'){const form=$('#care-sign-form'),draft={name:form.elements.signerName.value,relationship:form.elements.relationship.value,accepted:form.elements.accepted.checked};careState.typedSignature=form.elements.typedSignature?.value||careState.typedSignature;careState.signatureMode=target.dataset.mode;render();const n=$('#care-sign-form');n.elements.signerName.value=draft.name;n.elements.relationship.value=draft.relationship;n.elements.relationship.dispatchEvent(new Event('select-sync'));n.elements.accepted.checked=draft.accepted;return;}
  if(action==='signature-clear'){careState.strokes=[];const c=$('#care-signature-canvas');c?.getContext('2d').clearRect(0,0,600,180);return;}
  if(action==='activity-clear'){Object.assign(careState,{channel:'all',purpose:'all',delivery:'all',facility:'all',from:'',to:''});screen.query='';screen.page=1;render();return;}
  if(action==='activity-export'){const allowed=careStore.visibleFacilities().map(f=>f.id);const rows=careStore.db.messages.filter(m=>allowed.includes(m.facilityId));const csv=[['Time','Channel','Purpose','Recipient','Status'],...rows.map(m=>[m.at,m.channel,m.purpose,m.recipient,m.status])].map(row=>row.map(v=>'"'+String(v||'').replaceAll('"','""')+'"').join(',')).join('\r\n');careDownload(new Blob([csv],{type:'text/csv'}),'ent-communications.csv');return;}
  if(action==='advance-clock'){careStore.admin();const upcoming=careStore.db.residents.map(r=>r.visitDate).filter(Boolean).sort().at(-1);if(!upcoming)throw new Error('Book a clinic day first.');modal(`<h2>Preview the next clinic round?</h2><p>The demo clock will advance past ${date(upcoming)}. Consents for completed clinic days are archived, and new signing links are created.</p><div class="formfooter">${careB('Cancel','modal-close')}${careB('Advance demo clock','advance-confirm','','primary')}</div>`);return;}
  if(action==='advance-confirm'){const upcoming=careStore.db.residents.map(r=>r.visitDate).filter(Boolean).sort().at(-1);careStore.db.offset+=Math.max(1,Math.ceil((new Date(upcoming+'T12:00:00Z')-careStore.now())/864e5)+1);careStore.rollCycles();closeModal();careNavigate('facilities');toast('Next clinic round started. Previous consents archived.');return;}
  if(action==='reset-confirm'){modal(`<h2>Reset demo data?</h2><p>Facilities, residents, account changes and signatures in this demo will return to their sample values. You will be signed out. You can restore the previous data from Demo guide.</p><div class="formfooter">${careB('Cancel','modal-close')}${careB('Reset demo','reset','','primary')}</div>`);return;}
  if(action==='restore-demo'){careStore.restore();closeModal();careNavigate('facilities');toast('Previous demo data restored.');return;}
  if(action==='reset'){careStore.reset();careState.loginError='';careState.authError='';closeModal();careNavigate('login');toast('Demo data reset.');return;}
 }catch(err){if($('#dialog').open){const body=$('.modal-body');if(!body.querySelector('[role="alert"]'))body.insertAdjacentHTML('afterbegin',careError(err.message));}else toast(err.message);}
},true);
document.addEventListener('change',e=>{
 const t=e.target;if(t.matches('[data-care-show-password]')){const p=$('#care-login input[name="password"]');p.type=t.checked?'text':'password';}
 if(t.matches('[data-care-filter]')){careState[t.dataset.careFilter]=t.value;screen.page=1;render();}
 if(t.matches('#care-resident-form input[name="signer"]')){const rep=$('#care-representative'),needed=t.value!=='Self';rep.hidden=!needed;rep.querySelectorAll('input').forEach(i=>{i.disabled=!needed;i.required=needed;});const c=$('#care-resident-form button[value="send"]');if(c)c.textContent=needed?'Save & send request':'Save & sign now';}
 if(t.matches('[data-care-upload]')){const file=t.files[0];if(!file)return;const kind=t.dataset.careUpload,rid=t.dataset.id;(async()=>{try{const r=careStore.resident(rid);if(!careStore.facility(r.facilityId).drive)throw new Error('This facility has no Drive folder configured.');if(file.size>10*1024*1024||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw new Error('Choose a PDF, PNG or JPG smaller than 10 MB.');const key=r.id+'-'+kind+'-'+Date.now();await careFileDB('put',key,file);careStore.addDocument(rid,{kind,name:file.name,key,mime:file.type,size:file.size});render();toast('Document saved in this browser.');}catch(err){toast(err.message);}finally{t.value='';}})();}
});
document.addEventListener('submit',e=>{
 const form=e.target;if(!form.id.startsWith('care-'))return;e.preventDefault();e.stopImmediatePropagation();if(!form.reportValidity())return;const d=new FormData(form),data=Object.fromEntries(d);try{
 if(form.id==='care-login'){const u=careStore.login(data.username,data.password);careState.loginError='';careState.authError='';careState.facility='all';careNavigate(u.role==='Admin'?'facilities':'residents');}
 if(form.id==='care-resident-form'){const payload={facilityId:data.facilityId,name:data.name.trim(),dob:data.dob,room:data.room.trim(),signer:data.signer};if(data.signer!=='Self')payload.rep={name:data.repName.trim(),email:data.repEmail.trim(),phone:data.repPhone.replace(/[\s()-]/g,'')};const r=careStore.saveResident(payload,form.dataset.id||null);let message='Resident saved.';if(e.submitter?.value==='send'&&r.signer!=='Self'){const results=careStore.send(r.id);message=results.every(d=>d.status==='Failed')?'Resident saved. Delivery failed; check contact details.':results.some(d=>d.status==='Failed')?'Resident saved. One delivery channel failed.':'Resident saved; demo request delivered.';}careNavigate(e.submitter?.value==='send'&&r.signer==='Self'?'sign?token='+r.token:'resident?id='+r.id);toast(message);}
 if(form.id==='care-facility-form'){const f=careStore.addFacility(data);careNavigate('facility?fid='+f.id);toast('Facility created.');}
 if(form.id==='care-threshold-form'){careStore.updateThreshold(form.dataset.id,Number(data.threshold));closeModal();render();toast('Threshold updated.');}
 if(form.id==='care-schedule-form'){const n=careStore.schedule(form.dataset.id,data.day,form.dataset.change==='true');closeModal();render();toast(n+' residents scheduled.');}
 if(form.id==='care-account-form'){careStore.account(data,form.dataset.id||null);closeModal();render();toast('Staff account saved.');}
 if(form.id==='care-account-password'){careStore.resetPassword(form.dataset.id,data.password);closeModal();render();toast('Password reset; staff sessions revoked.');}
 if(form.id==='care-profile-form'){careStore.profile({name:data.name.trim(),email:data.email.trim()});render();toast('Profile saved.');}
 if(form.id==='care-preferences-form'){careStore.profile({timezone:data.timezone,theme:data.theme});setColorTheme(data.theme==='system'?matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light':data.theme);render();toast('Preferences saved.');}
 if(form.id==='care-password-form'){if(data.next!==data.confirm)throw new Error('The new passwords do not match.');careStore.password(data.current,data.next);careNavigate('login');toast('Password changed. Sign in again.');}
 if(form.id==='care-sign-form'){const r=careStore.signing(form.dataset.token),signature=careState.signatureMode==='type'?[{text:data.typedSignature.trim()}]:careState.strokes.filter(s=>s.length>1);if(!signature.length||signature[0]?.text==='')throw new Error('Add your signature before continuing.');careStore.sign(form.dataset.token,{signerName:data.signerName.trim(),relationship:data.relationship,accepted:data.accepted==='on',signature,failPdf:!careStore.db.facilities.find(f=>f.id===r.facilityId)?.drive});careState.strokes=[];careState.typedSignature='';render();toast('Demo consent signed.');}
 }catch(err){if(form.id==='care-login'&&/deactivated|not an ENT/.test(err.message)){careState.authError=err.message.includes('deactivated')?'deactivated':'platform';render();}else careFormError(form,err);}
},true);
window.addEventListener('storage',e=>{if(e.key===CareDomain.KEY){try{careStore.db=JSON.parse(e.newValue);careStore.rollCycles();if($('#dialog').open)closeModal();render();}catch{}}else if(e.key===CareDomain.SESSION){try{careStore.session=JSON.parse(e.newValue);render();}catch{}}});
// Dates advance when returning to the prototype; do not let an old public link sign a new round.
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){careStore.rollCycles();render();}});
render();
function careAuthErrorPage(){const locked=careState.authError==='deactivated';return `<div class="care-message"><h1>${locked?'Account deactivated':'Not an ENT account'}</h1><p>${locked?'This account has been deactivated. Contact your administrator to restore access.':'This portal is for ENT care teams. Please use the ENT account your administrator gave you.'}</p>${careB('Back to sign in','login-again','','primary')}${careB('Choose a demo role','guide')}</div>`;}
function careDemoCases(){const open=careStore.db.residents.find(r=>r.status!=='Signed'&&r.rep&&r.status!=='Do not contact'),signed=careStore.db.residents.find(r=>r.status==='Signed');return [
 ['role-login','Administration','Sign in & role access','ENT admin, facility staff, deactivated and non-ENT accounts.','login'],
 ['resident-roster','Facilities','Resident action queue','Search, status and next actions for all residents.','residents'],
 ['consent-detail','Facilities','Signing request & delivery','Send / resend, reminders, copy and replace link, documents.','resident?id='+open?.id],
 ['consent-public','Facilities','Public signing page','Draw or type a signature and certify the fictional consent.','sign?token='+open?.token],
 ['consent-signed','Facilities','Already signed link','Signed receipt and PDF; cannot sign twice.','sign?token='+signed?.token],
 ['consent-invalid','Facilities','Invalid or replaced link','Request a fresh signing link from the facility.','sign?token=not-a-real-token'],
 ['care-settings','Administration','Account settings','Profile, preferences, password and revoke sessions.','settings'],
 ['care-messages','Administration','Communication activity','Email / SMS / voice, delivery failures and PCC alerts.','activity']
 ].map(([id,group,title,description,route])=>({id,group,title,description,route,layout:'Shared ENT workflow'}));}
function careCaptureForms(){return [...document.querySelectorAll('form[id^="care-"]')].map(f=>({id:f.id,representativeHidden:f.querySelector('#care-representative')?.hidden,controls:[...f.elements].filter(t=>t.name&&t.type!=='file').map(t=>({name:t.name,value:t.value,type:t.type,checked:t.checked,disabled:t.disabled,required:t.required}))}));}
function careRestoreForms(drafts){for(const draft of drafts){const f=document.getElementById(draft.id);if(!f)continue;for(const saved of draft.controls){const controls=[...f.elements].filter(t=>t.name===saved.name&&(saved.type!=='radio'||t.value===saved.value));for(const t of controls){if(t.type!=='radio')t.value=saved.value;t.checked=saved.checked;t.disabled=saved.disabled;t.required=saved.required;if(t.tagName==='SELECT')t.dispatchEvent(new Event('select-sync'));}}const panel=f.querySelector('#care-representative');if(panel)panel.hidden=draft.representativeHidden;}}
function carePDFPreview(r,title){const strokes=Array.isArray(r.signature)?r.signature.filter(Array.isArray):[];const drawing=strokes.map(s=>s.map(([x,y],i)=>(i?'L':'M')+Number(x).toFixed(2)+' '+Number(y).toFixed(2)).join(' ')).join(' ');return `<article class="care-paper-preview" aria-label="Signed consent preview"><header><small>ENT SENIOR CARE GROUP · FICTIONAL DEMO</small><h3>${esc(title||'Consent for ENT care')}</h3></header><dl><dt>Resident</dt><dd>${esc(r.name)}</dd><dt>Facility</dt><dd>${esc(careStore.db.facilities.find(f=>f.id===r.facilityId)?.name)}</dd><dt>Date of birth</dt><dd>${date(r.dob)}</dd></dl>${CareDomain.consentText.map(p=>`<p>${esc(p)}</p>`).join('')}<div class="care-paper-signature">${drawing?`<svg viewBox="0 0 600 180" aria-label="Recorded signature"><path d="${drawing}" fill="none" stroke="#202124" stroke-width="2.4" stroke-linecap="round"/></svg>`:`<span>${esc(r.signature?.[0]?.text||r.signerName||r.name)}</span>`}</div><p><strong>Signed by:</strong> ${esc(r.signerName)} (${esc(r.relationship||r.signer)})<br><strong>Signed at:</strong> ${careTime(r.signedAt)}</p></article>`;}
function careSyncOperations(){facilities=careStore.db.facilities.map((f,i)=>{const s=careStore.summary(f);return {id:i+1,careId:f.id,name:f.name,address:f.address,contact:f.contact,phone:f.phone,count:s.count,signed:s.signed,threshold:f.threshold,exam:s.exam,residents:careStore.db.residents.filter(r=>r.facilityId===f.id).map(r=>({...r,consent:r.status}))};});}
