/* Cliently library: Tasks Status, Universal Cards and component review gallery. */
function taskStatus(label,status='Todo'){
 if(isV2())return `<span class="status v2-task-status" data-status="${esc(status)}">${esc(label)}</span>`;
 const dots={Todo:['1f229','41f2f'],Inprogress:['a62df','1a734'],Review:['89f35','dd4ea'],Completed:['20e4b','6e4a3']}[status];
 return `<span class="task-status task-${status.toLowerCase()}">${themedAsset('assets/cliently/system/'+dots[0]+'.svg','assets/cliently/system/'+dots[1]+'.svg',6,6)}${esc(label)}</span>`;
}
function componentGallery(){
 const section=(title,copy,body)=>`<section class="kit-section"><div class="kit-spec"><div><h2>${title}</h2><p>${copy}</p></div><div>${body}</div></div></section>`;
 const actions=['','solid','primary','danger'].map(style=>button(style==='solid'?'Primary':style==='primary'?'Blue':style==='danger'?'Red':'Secondary','kit-feedback',style)).join('');
 const palette=[['Primary','--primary'],['Text','--ink'],['Supporting text','--muted'],['Border','--line'],['Page','--paper'],['Surface','--surface']];
 return section('Theme & palette','Light and Dark values from Cliently. Use Dark mode in the header to switch the entire application.',`<div class="token-grid">${palette.map(([name,token])=>`<div><div class="swatch" style="background:var(${token})"></div><strong>${name}</strong><small>${token}</small></div>`).join('')}</div>`)+
 section('Buttons','Small 32px, Medium 38px, Big 48px. Inter semibold, 8px/10px corners.',`<div class="component-stack"><div class="inline-actions">${actions}${button('Disabled','kit-feedback','','','disabled')}</div><div class="inline-actions"><button class="btn medium solid" data-action="kit-feedback">Medium · 38px</button><button class="btn big primary" data-action="kit-feedback">Big · 48px</button></div></div>`)+
 section('Input & select','48px fields, 20px/16px padding, 22px label slot. Focus #4D81E7; error #FF4935.',`<div class="formgrid">${field('Resident name','kit-name','Eleanor Bennett')}${field('Placeholder','kit-placeholder','','text','placeholder="Enter a name"')}${field('Disabled input','kit-disabled','Unavailable','text','disabled')}${field('Error state','kit-error','Invalid value','text','aria-label="Error state" aria-invalid="true" aria-describedby="kit-error-help"').replace('</label>','<small id="kit-error-help" class="field-error">Review the entered value.</small></label>')}<label class="field"><span>Patient match</span><select name="kit-match"><option>Matched</option><option>Possible match</option><option>No match</option></select></label><label class="field"><span>Disabled select</span><select disabled><option>Unavailable</option></select></label></div>`)+
 section('Checkbox & radio','Library controls: 24px; checkbox corners 6px. Form labels and disabled states share the same component.',`<div class="component-stack"><div class="inline-actions"><label class="checkline"><input type="checkbox"> Unchecked</label><label class="checkline"><input type="checkbox" checked> Checked</label><label class="checkline"><input type="checkbox" disabled> Disabled</label></div><div class="inline-actions"><label class="checkline"><input type="radio" name="kit-radio" value="one" checked> Option one</label><label class="checkline"><input type="radio" name="kit-radio" value="two"> Option two</label><label class="checkline"><input type="radio" disabled> Disabled</label></div></div>`)+
 section('Tasks Status','24px pills, 10px padding, 6px gap, original 6px status dots. Contact statuses keep their separate neutral style.',`<div class="inline-actions">${['Todo','Inprogress','Review','Completed'].map(s=>taskStatus(s,s)).join('')}</div><div class="inline-actions" style="margin-top:16px">${badge('Matched')}${badge('Needs verification')}${badge('Admin')}</div>`)+
 section('Universal Cards','Note, Tasks and Headcount variants from the component library. Shared 16px padding and 10px corners.',`<div class="universal-gallery"><article class="universal-card note-card"><div class="card-top">${themedAsset('assets/cliently/system/6f37d.svg','assets/cliently/system/ad0bc.svg',32,32)}${icon('metricMore')}</div><div><h3>Clinic preparation — Maple Grove</h3><p>Review census results and confirm resident consent before scheduling the next ENT clinic.</p></div><footer><span>${avatar(0)}Jordan Davis</span><time>Oct 7, 2026</time></footer></article><article class="universal-card task-card"><div class="card-top"><span class="task-due">${themedAsset('assets/cliently/system/1ad2a.svg','assets/cliently/system/1ad2a.svg',6,6)}Due Today</span>${icon('metricMore')}</div><h3>Review the census<br>for Maple Grove</h3><footer><span><span class="task-company">${companyIcon(0)}</span>ENT Care</span><span>${avatar(0,18)}${avatar(1,18)}</span></footer></article><article class="metric universal-headcount"><div class="metric-top"><span class="metric-label">Residents reviewed</span>${icon('metricMore')}</div><div class="metric-bottom"><strong class="metric-value">8</strong><span class="metric-note">Maple Grove Care Center</span></div></article></div>`)+
 section('Table & pagination','40px header, 54px rows, 12px cell padding. Page and rows-per-page controls work across all tables.',table(['Resident','Workflow status',''],Array.from({length:12},(_,i)=>`<tr><td>Sample resident ${i+1}</td><td>${taskStatus(i%2?'Review':'Completed',i%2?'Review':'Completed')}</td><td>${button('Review','kit-feedback','small')}</td></tr>`).join(''))+tableFoot(12,'sample residents'))+
 section('Typography','Inter 400 / 500 / 600. Manrope ExtraBold remains the brand wordmark.',`<div class="type-demo"><h1>Heading · 20 / 30</h1><h2>Modal title · 18 / 27</h2><p>Body · 14 / 21</p></div>`)+
 section('Figma sources','Component library and both dashboard themes.',`<p><a href="https://www.figma.com/design/Kn4d4FIOmy9KhOsgjkTgXr?node-id=6155-20444" target="_blank" rel="noopener">Cliently component library</a> · <a href="https://www.figma.com/design/Kn4d4FIOmy9KhOsgjkTgXr?node-id=6146-19085" target="_blank" rel="noopener">Dark Mode</a></p>`);
}
